/**
 * Copyright (c) 2026, Adrien Devresse <adev@adev.name>
 *
 * Boost Software License - Version 1.0
 *
 * Permission is hereby granted, free of charge, to any person or organization
 * obtaining a copy of the software and accompanying documentation covered by
 * this license (the "Software") to use, reproduce, display, distribute,
 * execute, and transmit the Software, and to prepare derivative works of the
 * Software, and to permit third-parties to whom the Software is furnished to
 * do so, all subject to the following:
 *
 * The copyright notices in the Software and this entire statement, including
 * the above license grant, this restriction and the following disclaimer,
 * must be included in all copies of the Software, in whole or in part, and
 * all derivative works of the Software, unless such copies or derivative
 * works are solely in the form of machine-executable object code generated by
 * a source language processor.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
 * SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE
 * FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
 * ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
 * DEALINGS IN THE SOFTWARE.
 *
 */
#pragma once

#include <array>
#include <cstdint>

//
// Official Random123 known answer test vectors for the ARS4x32 generator.
//
// These are the `ars4x32` lines of the `tests/kat_vectors` file shipped by
// the reference Random123 implementation
// (https://github.com/DEShawResearch/random123, v1.14.0). The reference runs
// them through the AES-NI implementation, so checking alea against them is a
// bit-to-bit validation against the official implementation, independent of
// the instruction set used by alea.
//
// Every vector is given as (rounds, counter, key, expected block), with the
// words in the same order as the reference.
//

namespace alea {
namespace test {
namespace ars_kat {

struct kat_vector {
  unsigned rounds;
  std::array<std::uint32_t, 4> counter;
  std::array<std::uint32_t, 4> key;
  std::array<std::uint32_t, 4> expected;
};

/// the three ars4x32 vectors of the reference `kat_vectors` file
inline constexpr std::array<kat_vector, 3> vectors{{
    // gen(0, 0)
    {10,
     {0x00000000U, 0x00000000U, 0x00000000U, 0x00000000U},
     {0x00000000U, 0x00000000U, 0x00000000U, 0x00000000U},
     {0x8d73ee19U, 0x506401efU, 0x13c2dbe4U, 0x0cbe9c0dU}},

    // gen(ctr = digits of pi, key = more digits of pi)
    {10,
     {0x243f6a88U, 0x85a308d3U, 0x13198a2eU, 0x03707344U},
     {0xa4093822U, 0x299f31d0U, 0x082efa98U, 0xec4e6c89U},
     {0xa516e7d6U, 0x8357ad74U, 0x5b59b3ecU, 0x8763fff3U}},

    // gen(ctr = fff..., key = fff... 0 0)
    {10,
     {0xffffffffU, 0xffffffffU, 0xffffffffU, 0xffffffffU},
     {0xffffffffU, 0xffffffffU, 0x00000000U, 0x00000000U},
     {0xbb3743b1U, 0x9f635551U, 0xecbc87fcU, 0xa19478a9U}},
}};

} // namespace ars_kat
} // namespace test
} // namespace alea
