/**
 * Copyright (c) 2026, Adrien Devresse <adev@adev.name>
 *
 * Boost Software License - Version 1.0
 *
 * Permission is hereby granted, free of charge, to any person or organization
 * obtaining a copy of the software and accompanying documentation covered by
 * this license (the "Software") to use, reproduce, display, distribute,
 * execute, and transmit the Software, and to prepare derivative works of the
 * Software, and to permit third-parties to whom the Software is furnished to
 * do so, all subject to the following:
 *
 * The copyright notices in the Software and this entire statement, including
 * the above license grant, this restriction and the following disclaimer,
 * must be included in all copies of the Software, in whole or in part, and
 * all derivative works of the Software, unless such copies or derivative
 * works are solely in the form of machine-executable object code generated by
 * a source language processor.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
 * SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE
 * FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
 * ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
 * DEALINGS IN THE SOFTWARE.
 *
 */

#define DOCTEST_CONFIG_IMPLEMENT_WITH_MAIN
#include "doctest/doctest.h"

#include <array>
#include <cstdint>
#include <limits>
#include <random>
#include <sstream>
#include <type_traits>

#include "alea/random.hpp"

#include "ars_kat.hpp"

//
// the ars generators must be usable in constant expressions: this also checks
// at compile time that the software implementation of the AES round function
// is correct, independently of the AES instructions the translation unit may
// be compiled with. The run time checks below exercise the optimized path
// when the platform provides it.
//

static_assert(alea::ars<5>{}(alea::ars<5>::domain_type{1, 2, 3, 4})[0] == 0x9fcb4d03U);
static_assert(alea::ars<7>{}(alea::ars<7>::domain_type{1, 2, 3, 4})[3] == 0x268d303eU);
static_assert(alea::ars<10>{}(alea::ars<10>::domain_type{1, 2, 3, 4})[1] == 0xd02b6c70U);

// the official Random123 known answers, evaluated at compile time through the
// software implementation
static_assert(alea::ars<10>(alea::ars<10>::key_type{0, 0, 0, 0})(alea::ars<10>::domain_type{0, 0, 0, 0})[0] ==
              0x8d73ee19U);
static_assert(alea::ars<10>(alea::ars<10>::key_type{0xa4093822U, 0x299f31d0U, 0x082efa98U, 0xec4e6c89U})(
                  alea::ars<10>::domain_type{0x243f6a88U, 0x85a308d3U, 0x13198a2eU, 0x03707344U})[0] == 0xa516e7d6U);
static_assert(alea::ars<10>(alea::ars<10>::key_type{0xffffffffU, 0xffffffffU, 0x00000000U, 0x00000000U})(
                  alea::ars<10>::domain_type{0xffffffffU, 0xffffffffU, 0xffffffffU, 0xffffffffU})[3] == 0xa19478a9U);

TEST_CASE("ars official Random123 known answers") {
  // these checks run through the instruction set selected for the build: on a
  // platform with AES instructions they validate the optimized implementation
  // against the official reference output, otherwise they validate the
  // software fallback
  for (const alea::test::ars_kat::kat_vector& vector : alea::test::ars_kat::vectors) {
    REQUIRE_EQ(vector.rounds, 10U);
    const auto block = alea::ars<10>{vector.key}(vector.counter);
    CHECK_EQ(block, vector.expected);
  }
}

TEST_CASE("ars golden values, default and reduced round counts") {
  SUBCASE("ars<5>") {
    const alea::ars<5> cipher;
    const auto block = cipher(alea::ars<5>::domain_type{1, 2, 3, 4});
    CHECK_EQ(block[0], 0x9fcb4d03U);
    CHECK_EQ(block[1], 0x5198c453U);
    CHECK_EQ(block[2], 0x15145ee9U);
    CHECK_EQ(block[3], 0x38c24f2bU);
  }

  SUBCASE("ars<7>, the default") {
    const alea::ars<7> cipher;
    const auto block = cipher(alea::ars<7>::domain_type{1, 2, 3, 4});
    CHECK_EQ(block[0], 0xb427c7f2U);
    CHECK_EQ(block[1], 0xee4ef3dfU);
    CHECK_EQ(block[2], 0x66d36578U);
    CHECK_EQ(block[3], 0x268d303eU);
  }

  SUBCASE("ars<10>") {
    const alea::ars<10> cipher;
    const auto block = cipher(alea::ars<10>::domain_type{1, 2, 3, 4});
    CHECK_EQ(block[0], 0xa9293eddU);
    CHECK_EQ(block[1], 0xd02b6c70U);
    CHECK_EQ(block[2], 0x7e9269a5U);
    CHECK_EQ(block[3], 0xfac97cc3U);
  }

  SUBCASE("ars<7> with a non zero key") {
    const alea::ars<7> cipher(alea::ars<7>::key_type{0x01234567U, 0x89abcdefU, 0xfedcba98U, 0x76543210U});
    const auto block = cipher(alea::ars<7>::domain_type{1, 2, 3, 4});
    CHECK_EQ(block[0], 0x1244cdd5U);
    CHECK_EQ(block[1], 0x6a6c57bdU);
    CHECK_EQ(block[2], 0xecba64e1U);
    CHECK_EQ(block[3], 0x911090acU);
  }

  SUBCASE("ars4x32 is the 7 rounds ars") {
    static_assert(std::is_same_v<alea::ars4x32, alea::ars<7>>, "the reference ars4x32 uses 7 rounds");
    static_assert(std::is_same_v<alea::ars_default, alea::ars4x32>, "the default generator must be ars4x32");
    static_assert(std::is_same_v<alea::ars_default::uint_type, std::uint32_t>,
                  "the default generator must use 32 bit words");
    CHECK(true);
  }
}

TEST_CASE("counter_engine ars golden stream") {
  alea::counter_engine<alea::ars4x32> engine;
  std::uint32_t val = 0;

  for (int i = 0; i <= 1000; ++i) {
    val = engine();
    if (i == 0) {
      CHECK_EQ(val, 0x7244c49cU);
    } else if (i == 10) {
      CHECK_EQ(val, 0x52d32f0fU);
    } else if (i == 100) {
      CHECK_EQ(val, 0xab7ae88eU);
    } else if (i == 1000) {
      CHECK_EQ(val, 0x4dad8f7eU);
    }
  }
}

TEST_CASE_TEMPLATE("ars api", Cbrng, alea::ars<5>, alea::ars<7>, alea::ars<10>) {
  using uint_type = typename Cbrng::uint_type;
  using key_type = typename Cbrng::key_type;
  using domain_type = typename Cbrng::domain_type;

  static_assert(Cbrng::number_of_rounds >= 1, "an ars generator must perform at least one round");

  // the default key is made of zeros, and the generator is stateless
  Cbrng default_cipher;
  CHECK_EQ(default_cipher.get_key(), key_type{});

  domain_type counter{};
  for (std::size_t i = 0; i < counter.size(); ++i) {
    counter[i] = static_cast<uint_type>(i + 1);
  }

  const auto first = default_cipher(counter);
  const auto second = default_cipher(counter);
  CHECK_EQ(first, second);

  // the key must be readable and updatable
  key_type key{};
  for (std::size_t i = 0; i < key.size(); ++i) {
    key[i] = static_cast<uint_type>(0x0123456789ABCDEFULL);
  }
  default_cipher.set_key(key);
  CHECK_EQ(default_cipher.get_key(), key);

  SUBCASE("equality is only based on the key") {
    Cbrng other(key);
    CHECK(default_cipher == other);
    CHECK_FALSE(default_cipher != other);

    other.set_key(key_type{});
    CHECK(default_cipher != other);
    CHECK_FALSE(default_cipher == other);
  }

  SUBCASE("different keys give different blocks") {
    const auto with_key = default_cipher(counter);
    const Cbrng cipher_zero_key;
    const auto without_key = cipher_zero_key(counter);

    std::size_t different_words = 0;
    for (std::size_t i = 0; i < with_key.size(); ++i) {
      different_words += (with_key[i] != without_key[i]) ? 1 : 0;
    }
    CHECK_GT(different_words, 0);
  }

  SUBCASE("ciphers are copy and move constructible") {
    const Cbrng copy(default_cipher);
    const Cbrng moved(default_cipher);
    CHECK(copy == default_cipher);
    CHECK(moved == default_cipher);
    CHECK_EQ(copy(counter), default_cipher(counter));
  }
}

TEST_CASE_TEMPLATE("counter_engine ars api", Cbrng, alea::ars<5>, alea::ars<7>, alea::ars<10>) {
  using engine_type = alea::counter_engine<Cbrng>;
  using result_type = typename engine_type::result_type;
  using key_type = typename engine_type::key_type;
  using ctr_type = typename engine_type::ctr_type;

  // engine requirements
  static_assert(std::is_unsigned_v<result_type>, "the result type must be unsigned");
  CHECK_EQ(engine_type::min(), static_cast<result_type>(0));
  CHECK_EQ(engine_type::max(), std::numeric_limits<result_type>::max());

  key_type key{};
  for (std::size_t i = 0; i < key.size(); ++i) {
    key[i] = static_cast<result_type>(i + 42);
  }

  SUBCASE("two engines with the same key give the same stream") {
    engine_type first(key);
    engine_type second;
    second.seed(key);

    for (int i = 0; i < 1000; ++i) {
      CHECK_EQ(first(), second());
    }
    CHECK(first == second);
    CHECK_FALSE(first != second);
  }

  SUBCASE("seed and get_key, get_counter") {
    engine_type engine;
    CHECK_EQ(engine.get_key(), key_type{});
    CHECK_EQ(engine.get_counter(), ctr_type{});

    engine.seed(key);
    CHECK_EQ(engine.get_key(), key);

    std::seed_seq seq{1, 2, 3, 4, 5, 6};
    engine_type from_seq(seq);
    CHECK_NE(engine.get_key(), from_seq.get_key());

    // the counter moves forward once the whole block has been consumed
    engine_type stepper(key);
    const std::size_t block_size = stepper.get_counter().size();
    for (std::size_t i = 0; i < block_size; ++i) {
      (void)stepper();
    }
    CHECK_EQ(stepper.get_counter(), ctr_type{1});
  }

  SUBCASE("generate_block is the encryption of the incremented counter") {
    engine_type engine(key);
    const Cbrng cipher(key);
    const ctr_type block = engine.generate_block();

    ctr_type expected_ctr{};
    expected_ctr[0] = 1;
    CHECK_EQ(block, cipher(expected_ctr));
    CHECK_EQ(engine.get_counter(), expected_ctr);
  }

  SUBCASE("discard is consistent with consuming one by one") {
    {
      engine_type engine(key);
      engine_type clone(key);
      clone.discard(0);
      CHECK_EQ(engine(), clone());
    }
    {
      engine_type engine(key);
      engine_type clone(key);
      for (int i = 0; i < 100; ++i) {
        (void)engine();
      }
      clone.discard(100);
      CHECK_EQ(engine(), clone());
    }
    {
      engine_type engine(key);
      engine_type clone(key);
      const std::size_t inc_n = 1181;
      for (std::size_t i = 0; i < inc_n; ++i) {
        (void)engine();
      }
      clone.discard(inc_n);
      CHECK_EQ(engine(), clone());
    }
    {
      engine_type engine(key);
      engine_type clone(key);
      (void)engine();
      clone.discard(1);
      CHECK_EQ(engine(), clone());
    }
  }

  SUBCASE("engines are copy constructible and stream printable") {
    engine_type engine(key);
    for (int i = 0; i < 3; ++i) {
      (void)engine();
    }

    const engine_type copy(engine);
    CHECK(copy == engine);

    std::ostringstream os;
    os << engine;
    CHECK_FALSE(os.str().empty());
  }

  SUBCASE("the engine is usable with the std distributions") {
    std::uniform_int_distribution<result_type> int_dist(0, 100);
    std::uniform_real_distribution<double> real_dist(0.0, 1.0);

    engine_type engine(key);
    std::uint64_t sum = 0;
    const std::size_t n_normalize = 100000;

    for (std::size_t i = 0; i < n_normalize; ++i) {
      const result_type val = int_dist(engine);
      CHECK_GE(val, static_cast<result_type>(0));
      CHECK_LE(val, static_cast<result_type>(100));
      sum += val;

      const double dval = real_dist(engine);
      CHECK_GE(dval, 0.0);
      CHECK_LE(dval, 1.0);
    }

    const std::uint64_t mean = sum / n_normalize;
    CHECK_GE(mean, 49);
    CHECK_LE(mean, 51);
  }
}
