/**
 * Copyright (c) 2026, Adrien Devresse <adev@adev.name>
 *
 * Boost Software License - Version 1.0
 *
 * Permission is hereby granted, free of charge, to any person or organization
 * obtaining a copy of the software and accompanying documentation covered by
 * this license (the "Software") to use, reproduce, display, distribute,
 * execute, and transmit the Software, and to prepare derivative works of the
 * Software, and to permit third-parties to whom the Software is furnished to
 * do so, all subject to the following:
 *
 * The copyright notices in the Software and this entire statement, including
 * the above license grant, this restriction and the following disclaimer,
 * must be included in all copies of the Software, in whole or in part, and
 * all derivative works of the Software, unless such copies or derivative
 * works are solely in the form of machine-executable object code generated by
 * a source language processor.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
 * SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE
 * FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
 * ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
 * DEALINGS IN THE SOFTWARE.
 *
 */

#define DOCTEST_CONFIG_IMPLEMENT_WITH_MAIN
#include "doctest/doctest.h"

#include <algorithm>
#include <array>
#include <cstddef>
#include <string>
#include <string_view>
#include <vector>

#include "alea/blake2.hpp"
#include "alea/hex.hpp"

//
// Known answer tests for the alea BLAKE2b and BLAKE2s implementations. The
// expected digests have been cross checked against the BLAKE2 reference
// implementation, Python hashlib, b2sum and OpenSSL. Every message is also
// hashed with a variety of chunk sizes to exercise the streaming interface,
// and the result must be identical to the one shot digest.
//

namespace {

std::vector<std::byte> to_bytes(std::string_view text) {
  std::vector<std::byte> data(text.size());
  for (std::size_t i = 0; i < text.size(); ++i) {
    data[i] = static_cast<std::byte>(static_cast<unsigned char>(text[i]));
  }
  return data;
}

std::vector<std::byte> pattern(std::size_t size, std::size_t multiplier, std::size_t offset) {
  std::vector<std::byte> data(size);
  for (std::size_t i = 0; i < size; ++i) {
    data[i] = static_cast<std::byte>((i * multiplier + offset) & 0xffu);
  }
  return data;
}

template <typename Hasher> std::string digest_hex(const std::vector<std::byte>& data) {
  Hasher hasher;
  hasher.update(std::span<const std::byte>(data.data(), data.size()));
  return alea::to_hex(hasher.finalize());
}

template <typename Hasher> std::string digest_hex_chunked(const std::vector<std::byte>& data, std::size_t chunk) {
  Hasher hasher;
  for (std::size_t position = 0; position < data.size();) {
    const std::size_t size = std::min(chunk, data.size() - position);
    hasher.update(std::span<const std::byte>(data.data() + position, size));
    position += size;
  }
  return alea::to_hex(hasher.finalize());
}

template <typename Hasher> void check_known_answer(const std::vector<std::byte>& message, std::string_view expected) {
  CHECK(digest_hex<Hasher>(message) == expected);
  for (const std::size_t chunk : {1u, 2u, 3u, 63u, 64u, 65u, 127u, 128u, 129u, 200u}) {
    CHECK(digest_hex_chunked<Hasher>(message, chunk) == expected);
  }
}

// the hashers are usable during constant evaluation
constexpr std::array<std::byte, 3> abc_message = {static_cast<std::byte>('a'), static_cast<std::byte>('b'),
                                                  static_cast<std::byte>('c')};

constexpr alea::blake2b::digest_type blake2b_abc() {
  alea::blake2b hasher;
  hasher.update(abc_message);
  return hasher.finalize();
}

constexpr alea::blake2s::digest_type blake2s_abc() {
  alea::blake2s hasher;
  hasher.update(abc_message);
  return hasher.finalize();
}

static_assert(blake2b_abc()[0] == static_cast<std::byte>(0xba));
static_assert(blake2s_abc()[0] == static_cast<std::byte>(0x50));

} // namespace

TEST_CASE("blake2b known answers") {
  check_known_answer<alea::blake2b>(to_bytes(""), "786a02f742015903c6c6fd852552d272912f4740e15847618a86e217f71f5419d25e"
                                                  "1031afee585313896444934eb04b903a685b1448b755d56f701afe9be2ce");
  check_known_answer<alea::blake2b>(to_bytes("abc"), "ba80a53f981c4d0d6a2797b69f12f6e94c212f14685ac4b74b12bb6fdbffa2d17"
                                                     "d87c5392aab792dc252d5de4533cc9518d38aa8dbf1925ab92386edd4009923");
  check_known_answer<alea::blake2b>(to_bytes("The quick brown fox jumps over the lazy dog"),
                                    "a8add4bdddfd93e4877d2746e62817b116364a1fa7bc148d95090bc7333b3673f82401cf7aa2e4cb1e"
                                    "cd90296e3f14cb5413f8ed77be73045b13914cdcd6a918");
  check_known_answer<alea::blake2b>(pattern(64, 1, 0),
                                    "2fc6e69fa26a89a5ed269092cb9b2a449a4409a7a44011eecad13d7c4b0456602d402fa5844f1a7a75"
                                    "8136ce3d5d8d0e8b86921ffff4f692dd95bdc8e5ff0052");
  check_known_answer<alea::blake2b>(pattern(128, 1, 0),
                                    "2319e3789c47e2daa5fe807f61bec2a1a6537fa03f19ff32e87eecbfd64b7e0e8ccff439ac333b040f"
                                    "19b0c4ddd11a61e24ac1fe0f10a039806c5dcc0da3d115");
  check_known_answer<alea::blake2b>(pattern(129, 13, 0),
                                    "4b9b391fc3021a5c58ab1ad6ed0c50d30fdbfb7a8fb5efe8455954dc27ab6b319741cff453f9909f49"
                                    "ee523d7f998556af9c2aff3a4d943e1a95f537206ae05a");
  check_known_answer<alea::blake2b>(pattern(1000, 7, 3),
                                    "4bdd2c9cf31d797a81d245c989ffb7515143ca345c66f73087dd5c58bf642bf083ba16894eab79e3b0"
                                    "8d5126404d833e7510271b50be36a7b7cbbb46f5c89fac");
}

TEST_CASE("blake2s known answers") {
  check_known_answer<alea::blake2s>(to_bytes(""), "69217a3079908094e11121d042354a7c1f55b6482ca1a51e1b250dfd1ed0eef9");
  check_known_answer<alea::blake2s>(to_bytes("abc"),
                                    "508c5e8c327c14e2e1a72ba34eeb452f37458b209ed63a294d999b4c86675982");
  check_known_answer<alea::blake2s>(to_bytes("The quick brown fox jumps over the lazy dog"),
                                    "606beeec743ccbeff6cbcdf5d5302aa855c256c29b88c8ed331ea1a6bf3c8812");
  check_known_answer<alea::blake2s>(pattern(64, 1, 0),
                                    "56f34e8b96557e90c1f24b52d0c89d51086acf1b00f634cf1dde9233b8eaaa3e");
  check_known_answer<alea::blake2s>(pattern(128, 1, 0),
                                    "1fa877de67259d19863a2a34bcc6962a2b25fcbf5cbecd7ede8f1fa36688a796");
  check_known_answer<alea::blake2s>(pattern(129, 13, 0),
                                    "97dd1922d5d2fe24c5f68e01803ce18bf52292ec671888bfd8d73ce1db50572d");
  check_known_answer<alea::blake2s>(pattern(1000, 7, 3),
                                    "02a016193469710efadf8fb005ca19b509331cb847df5598cc0794bded669681");
}

TEST_CASE("blake2b and blake2s can be reset and reused") {
  const std::vector<std::byte> message = pattern(333, 11, 5);
  const std::string expected_b = digest_hex<alea::blake2b>(message);
  const std::string expected_s = digest_hex<alea::blake2s>(message);

  alea::blake2b hasher_b;
  hasher_b.update(to_bytes("some previous content"));
  hasher_b.reset();
  CHECK(alea::to_hex(hasher_b.finalize()) == digest_hex<alea::blake2b>(to_bytes("")));

  hasher_b.reset();
  hasher_b.update(message);
  CHECK(alea::to_hex(hasher_b.finalize()) == expected_b);

  alea::blake2s hasher_s;
  hasher_s.update(to_bytes("some previous content"));
  hasher_s.reset();
  hasher_s.update(message);
  CHECK(alea::to_hex(hasher_s.finalize()) == expected_s);
}
