/**
 * Copyright (c) 2026, Adrien Devresse <adev@adev.name>
 *
 * Boost Software License - Version 1.0
 *
 * Permission is hereby granted, free of charge, to any person or organization
 * obtaining a copy of the software and accompanying documentation covered by
 * this license (the "Software") to use, reproduce, display, distribute,
 * execute, and transmit the Software, and to prepare derivative works of the
 * Software, and to permit third-parties to whom the Software is furnished to
 * do so, all subject to the following:
 *
 * The copyright notices in the Software and this entire statement, including
 * the above license grant, this restriction and the following disclaimer,
 * must be included in all copies of the Software, in whole or in part, and
 * all derivative works of the Software, unless such copies or derivative
 * works are solely in the form of machine-executable object code generated by
 * a source language processor.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
 * SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE
 * FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
 * ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
 * DEALINGS IN THE SOFTWARE.
 *
 */

#define DOCTEST_CONFIG_IMPLEMENT_WITH_MAIN
#include "doctest/doctest.h"

#include <cstdint>
#include <limits>
#include <random>
#include <sstream>
#include <type_traits>

#include "alea/random.hpp"

//
// the philox generators must be usable in constant expressions: this also
// checks at compile time that the cipher is deterministic and stateless
//

static_assert(alea::philox4x64{}(alea::philox4x64::domain_type{1, 2, 3, 4})[0] == 5012960473186433633ULL);
static_assert(alea::philox2x32{}(alea::philox2x32::domain_type{1, 2})[1] == 2705655604U);

TEST_CASE("philox golden values, 32 bits") {
  SUBCASE("philox2x32") {
    alea::philox2x32 cipher;
    const auto block = cipher(alea::philox2x32::domain_type{1, 2});
    CHECK_EQ(block[0], 265829170U);
    CHECK_EQ(block[1], 2705655604U);
    static_assert(std::is_same_v<alea::philox2x32::uint_type, std::uint32_t>, "philox2x32 must use 32 bit words");
    static_assert(std::is_same_v<alea::philox2x32::key_type, std::array<std::uint32_t, 1>>,
                  "philox2x32 must use a single key word");
  }

  SUBCASE("philox4x32") {
    alea::philox4x32 cipher;
    const auto block = cipher(alea::philox4x32::domain_type{1, 2, 3, 4});
    CHECK_EQ(block[0], 2302483313U);
    CHECK_EQ(block[1], 2117282442U);
    CHECK_EQ(block[2], 995907209U);
    CHECK_EQ(block[3], 2728275945U);
    static_assert(std::is_same_v<alea::philox4x32::key_type, std::array<std::uint32_t, 2>>,
                  "philox4x32 must use two key words");
  }
}

TEST_CASE("philox golden values, 64 bits") {
  SUBCASE("philox2x64") {
    alea::philox2x64 cipher;
    const auto block = cipher(alea::philox2x64::domain_type{1, 2});
    CHECK_EQ(block[0], 3070252000352541757ULL);
    CHECK_EQ(block[1], 5823729036131133347ULL);
  }

  SUBCASE("philox4x64") {
    alea::philox4x64 cipher;
    const auto block = cipher(alea::philox4x64::domain_type{1, 2, 3, 4});
    CHECK_EQ(block[0], 5012960473186433633ULL);
    CHECK_EQ(block[1], 12081579199819527121ULL);
    CHECK_EQ(block[2], 4264790475553368732ULL);
    CHECK_EQ(block[3], 6866478666125097096ULL);
  }

  SUBCASE("philox with a non zero key") {
    const alea::philox4x64 cipher(alea::philox4x64::key_type{0x0123456789ABCDEFULL, 0xFEDCBA9876543210ULL});
    const auto block = cipher(alea::philox4x64::domain_type{1, 2, 3, 4});
    CHECK_EQ(block[0], 5730702193320826339ULL);
    CHECK_EQ(block[1], 17407678461925783020ULL);
    CHECK_EQ(block[2], 12592623786743107940ULL);
    CHECK_EQ(block[3], 16977972419026567409ULL);
  }

  SUBCASE("philox_default is philox4x64") {
    static_assert(std::is_same_v<alea::philox_default, alea::philox4x64>, "the default generator must be philox4x64");
    static_assert(std::is_same_v<alea::philox_default::uint_type, std::uint64_t>,
                  "the default generator must use 64 bit words");
    CHECK(true);
  }
}

TEST_CASE("counter_engine philox golden stream, 32 bits") {
  {
    alea::counter_engine<alea::philox2x32> engine;
    std::uint32_t val = 0;
    for (int i = 0; i <= 1000; ++i) {
      val = engine();
      if (i == 0) {
        CHECK_EQ(val, 1597692779U);
      } else if (i == 10) {
        CHECK_EQ(val, 2098432546U);
      } else if (i == 100) {
        CHECK_EQ(val, 2638244903U);
      } else if (i == 1000) {
        CHECK_EQ(val, 2499856217U);
      }
    }
  }

  {
    alea::counter_engine<alea::philox4x32> engine;
    std::uint32_t val = 0;
    for (int i = 0; i <= 1000; ++i) {
      val = engine();
      if (i == 0) {
        CHECK_EQ(val, 159317863U);
      } else if (i == 10) {
        CHECK_EQ(val, 1782871206U);
      } else if (i == 100) {
        CHECK_EQ(val, 3604111513U);
      } else if (i == 1000) {
        CHECK_EQ(val, 1721865298U);
      }
    }
  }
}

TEST_CASE("counter_engine philox golden stream, 64 bits") {
  {
    alea::counter_engine<alea::philox2x64> engine;
    std::uint64_t val = 0;
    for (int i = 0; i <= 1000; ++i) {
      val = engine();
      if (i == 0) {
        CHECK_EQ(val, 12372236411854687181ULL);
      } else if (i == 10) {
        CHECK_EQ(val, 8154894582262333314ULL);
      } else if (i == 100) {
        CHECK_EQ(val, 307372356048947528ULL);
      } else if (i == 1000) {
        CHECK_EQ(val, 10575809911605703474ULL);
      }
    }
  }

  {
    alea::counter_engine<alea::philox4x64> engine;
    std::uint64_t val = 0;
    for (int i = 0; i <= 1000; ++i) {
      val = engine();
      if (i == 0) {
        CHECK_EQ(val, 10411612076246414556ULL);
      } else if (i == 10) {
        CHECK_EQ(val, 3598048050090122770ULL);
      } else if (i == 100) {
        CHECK_EQ(val, 14569730162940421351ULL);
      } else if (i == 1000) {
        CHECK_EQ(val, 2458230141597846546ULL);
      }
    }
  }
}

TEST_CASE_TEMPLATE("philox api", Cbrng, alea::philox2x32, alea::philox4x32, alea::philox2x64, alea::philox4x64) {
  using uint_type = typename Cbrng::uint_type;
  using key_type = typename Cbrng::key_type;
  using domain_type = typename Cbrng::domain_type;

  CHECK_EQ(Cbrng::number_of_rounds, 10U);

  // the default key is made of zeros, and the generator is stateless
  Cbrng default_cipher;
  CHECK_EQ(default_cipher.get_key(), key_type{});

  domain_type counter{};
  for (std::size_t i = 0; i < counter.size(); ++i) {
    counter[i] = static_cast<uint_type>(i + 1);
  }

  const auto first = default_cipher(counter);
  const auto second = default_cipher(counter);
  CHECK_EQ(first, second);

  // the key must be readable and updatable
  key_type key{};
  for (std::size_t i = 0; i < key.size(); ++i) {
    key[i] = static_cast<uint_type>(0x0123456789ABCDEFULL);
  }
  default_cipher.set_key(key);
  CHECK_EQ(default_cipher.get_key(), key);

  SUBCASE("equality is only based on the key") {
    Cbrng other(key);
    CHECK(default_cipher == other);
    CHECK_FALSE(default_cipher != other);

    other.set_key(key_type{});
    CHECK(default_cipher != other);
    CHECK_FALSE(default_cipher == other);
  }

  SUBCASE("different keys give different blocks") {
    const auto with_key = default_cipher(counter);
    const Cbrng cipher_zero_key;
    const auto without_key = cipher_zero_key(counter);

    std::size_t different_words = 0;
    for (std::size_t i = 0; i < with_key.size(); ++i) {
      different_words += (with_key[i] != without_key[i]) ? 1 : 0;
    }
    CHECK_GT(different_words, 0);
  }

  SUBCASE("ciphers are copy and move constructible") {
    const Cbrng copy(default_cipher);
    const Cbrng moved(default_cipher);
    CHECK(copy == default_cipher);
    CHECK(moved == default_cipher);
    CHECK_EQ(copy(counter), default_cipher(counter));
  }
}

TEST_CASE_TEMPLATE("counter_engine philox api", Cbrng, alea::philox2x32, alea::philox4x32, alea::philox2x64,
                   alea::philox4x64) {
  using engine_type = alea::counter_engine<Cbrng>;
  using result_type = typename engine_type::result_type;
  using key_type = typename engine_type::key_type;
  using ctr_type = typename engine_type::ctr_type;

  // engine requirements
  static_assert(std::is_unsigned_v<result_type>, "the result type must be unsigned");
  CHECK_EQ(engine_type::min(), static_cast<result_type>(0));
  CHECK_EQ(engine_type::max(), std::numeric_limits<result_type>::max());

  key_type key{};
  for (std::size_t i = 0; i < key.size(); ++i) {
    key[i] = static_cast<result_type>(i + 42);
  }

  SUBCASE("two engines with the same key give the same stream") {
    engine_type first(key);
    engine_type second;
    second.seed(key);

    for (int i = 0; i < 1000; ++i) {
      CHECK_EQ(first(), second());
    }
    CHECK(first == second);
    CHECK_FALSE(first != second);
  }

  SUBCASE("seed and get_key, get_counter") {
    engine_type engine;
    CHECK_EQ(engine.get_key(), key_type{});
    CHECK_EQ(engine.get_counter(), ctr_type{});

    engine.seed(key);
    CHECK_EQ(engine.get_key(), key);

    std::seed_seq seq{1, 2, 3, 4, 5, 6};
    engine_type from_seq(seq);
    CHECK_NE(engine.get_key(), from_seq.get_key());

    // the counter moves forward once the whole block has been consumed
    engine_type stepper(key);
    const std::size_t block_size = stepper.get_counter().size();
    for (std::size_t i = 0; i < block_size; ++i) {
      (void)stepper();
    }
    CHECK_EQ(stepper.get_counter(), ctr_type{1});
  }

  SUBCASE("generate_block is the encryption of the incremented counter") {
    engine_type engine(key);
    const Cbrng cipher(key);
    const ctr_type block = engine.generate_block();

    ctr_type expected_ctr{};
    expected_ctr[0] = 1;
    CHECK_EQ(block, cipher(expected_ctr));
    CHECK_EQ(engine.get_counter(), expected_ctr);
  }

  SUBCASE("discard is consistent with consuming one by one") {
    {
      engine_type engine(key);
      engine_type clone(key);
      clone.discard(0);
      CHECK_EQ(engine(), clone());
    }
    {
      engine_type engine(key);
      engine_type clone(key);
      for (int i = 0; i < 100; ++i) {
        (void)engine();
      }
      clone.discard(100);
      CHECK_EQ(engine(), clone());
    }
    {
      engine_type engine(key);
      engine_type clone(key);
      const std::size_t inc_n = 1181;
      for (std::size_t i = 0; i < inc_n; ++i) {
        (void)engine();
      }
      clone.discard(inc_n);
      CHECK_EQ(engine(), clone());
    }
    {
      engine_type engine(key);
      engine_type clone(key);
      (void)engine();
      clone.discard(1);
      CHECK_EQ(engine(), clone());
    }
  }

  SUBCASE("discard supports increments larger than a 32 bit word") {
    engine_type engine(key);
    engine_type clone(key);

    const std::uintmax_t max_val = std::numeric_limits<std::uintmax_t>::max();
    const std::size_t factor = 50;
    const std::uintmax_t small_inc = max_val / 16 / factor;
    const std::uintmax_t big_inc = small_inc * factor;

    for (std::size_t i = 0; i < factor; ++i) {
      engine.discard(small_inc);
    }
    clone.discard(big_inc);

    CHECK_EQ(engine.get_counter(), clone.get_counter());
    CHECK_EQ(engine(), clone());
  }

  SUBCASE("engines are copy constructible and stream printable") {
    engine_type engine(key);
    for (int i = 0; i < 3; ++i) {
      (void)engine();
    }

    const engine_type copy(engine);
    CHECK(copy == engine);

    std::ostringstream os;
    os << engine;
    CHECK_FALSE(os.str().empty());
  }

  SUBCASE("the engine is usable with the std distributions") {
    std::uniform_int_distribution<result_type> int_dist(0, 100);
    std::uniform_real_distribution<double> real_dist(0.0, 1.0);

    engine_type engine(key);
    std::uint64_t sum = 0;
    const std::size_t n_normalize = 100000;

    for (std::size_t i = 0; i < n_normalize; ++i) {
      const result_type val = int_dist(engine);
      CHECK_GE(val, static_cast<result_type>(0));
      CHECK_LE(val, static_cast<result_type>(100));
      sum += val;

      const double dval = real_dist(engine);
      CHECK_GE(dval, 0.0);
      CHECK_LE(dval, 1.0);
    }

    const std::uint64_t mean = sum / n_normalize;
    CHECK_GE(mean, 49);
    CHECK_LE(mean, 51);
  }
}
