/**
 * Copyright (c) 2026, Adrien Devresse <adev@adev.name>
 *
 * Boost Software License - Version 1.0
 *
 * Permission is hereby granted, free of charge, to any person or organization
 * obtaining a copy of the software and accompanying documentation covered by
 * this license (the "Software") to use, reproduce, display, distribute,
 * execute, and transmit the Software, and to prepare derivative works of the
 * Software, and to permit third-parties to whom the Software is furnished to
 * do so, all subject to the following:
 *
 * The copyright notices in the Software and this entire statement, including
 * the above license grant, this restriction and the following disclaimer,
 * must be included in all copies of the Software, in whole or in part, and
 * all derivative works of the Software, unless such copies or derivative
 * works are solely in the form of machine-executable object code generated by
 * a source language processor.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
 * SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE
 * FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
 * ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
 * DEALINGS IN THE SOFTWARE.
 *
 */

#define DOCTEST_CONFIG_IMPLEMENT_WITH_MAIN
#include "doctest/doctest.h"

#include <algorithm>
#include <array>
#include <cstddef>
#include <string>
#include <string_view>
#include <vector>

#include "alea/hex.hpp"
#include "alea/sha256.hpp"

//
// Known answer tests for the alea SHA-256 implementation. The expected
// digests have been cross checked against a reference implementation, Python
// hashlib, OpenSSL and the FIPS 180-4 examples. Every message is also hashed
// with a variety of chunk sizes to exercise the streaming interface.
//

namespace {

std::vector<std::byte> to_bytes(std::string_view text) {
  std::vector<std::byte> data(text.size());
  for (std::size_t i = 0; i < text.size(); ++i) {
    data[i] = static_cast<std::byte>(static_cast<unsigned char>(text[i]));
  }
  return data;
}

std::vector<std::byte> pattern(std::size_t size, std::size_t multiplier, std::size_t offset) {
  std::vector<std::byte> data(size);
  for (std::size_t i = 0; i < size; ++i) {
    data[i] = static_cast<std::byte>((i * multiplier + offset) & 0xffu);
  }
  return data;
}

std::string digest_hex(const std::vector<std::byte>& data) {
  alea::sha256 hasher;
  hasher.update(std::span<const std::byte>(data.data(), data.size()));
  return alea::to_hex(hasher.finalize());
}

std::string digest_hex_chunked(const std::vector<std::byte>& data, std::size_t chunk) {
  alea::sha256 hasher;
  for (std::size_t position = 0; position < data.size();) {
    const std::size_t size = std::min(chunk, data.size() - position);
    hasher.update(std::span<const std::byte>(data.data() + position, size));
    position += size;
  }
  return alea::to_hex(hasher.finalize());
}

void check_known_answer(const std::vector<std::byte>& message, std::string_view expected) {
  CHECK(digest_hex(message) == expected);
  for (const std::size_t chunk : {1u, 2u, 3u, 55u, 56u, 57u, 63u, 64u, 65u, 200u}) {
    CHECK(digest_hex_chunked(message, chunk) == expected);
  }
}

// the hasher is usable during constant evaluation
constexpr std::array<std::byte, 3> abc_message = {static_cast<std::byte>('a'), static_cast<std::byte>('b'),
                                                  static_cast<std::byte>('c')};

constexpr alea::sha256::digest_type sha256_abc() {
  alea::sha256 hasher;
  hasher.update(abc_message);
  return hasher.finalize();
}

static_assert(sha256_abc()[0] == static_cast<std::byte>(0xba));

} // namespace

TEST_CASE("sha256 known answers") {
  check_known_answer(to_bytes(""), "e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855");
  check_known_answer(to_bytes("abc"), "ba7816bf8f01cfea414140de5dae2223b00361a396177a9cb410ff61f20015ad");
  check_known_answer(to_bytes("abcdbcdecdefdefgefghfghighijhijkijkljklmklmnlmnomnopnopq"),
                     "248d6a61d20638b8e5c026930c3e6039a33ce45964ff2167f6ecedd419db06c1");
  check_known_answer(to_bytes("The quick brown fox jumps over the lazy dog"),
                     "d7a8fbb307d7809469ca9abcb0082e4f8d5651e46d3cdb762d02d0bf37c9e592");
  check_known_answer(pattern(64, 1, 0), "fdeab9acf3710362bd2658cdc9a29e8f9c757fcf9811603a8c447cd1d9151108");
  check_known_answer(pattern(128, 1, 0), "471fb943aa23c511f6f72f8d1652d9c880cfa392ad80503120547703e56a2be5");
  check_known_answer(pattern(129, 13, 0), "37ae30c9543e4d0abc074e3fdf4b8d037f0dc97cc3e5a835f1fbfa0751bfc057");
  check_known_answer(pattern(1000, 7, 3), "1e9bc38cbf860b9ec31918b065f9b52476c549a782e0e7990bed8ce3868d2371");
  check_known_answer(std::vector<std::byte>(1000000, static_cast<std::byte>('a')),
                     "cdc76e5c9914fb9281a1c7e284d73e67f1809a48a497200e046d39ccc7112cd0");
}

TEST_CASE("sha256 can be reset and reused") {
  const std::vector<std::byte> message = pattern(333, 11, 5);
  const std::string expected = digest_hex(message);

  alea::sha256 hasher;
  hasher.update(to_bytes("some previous content"));
  hasher.reset();
  CHECK(alea::to_hex(hasher.finalize()) == digest_hex(to_bytes("")));

  hasher.reset();
  hasher.update(message);
  CHECK(alea::to_hex(hasher.finalize()) == expected);
}
