/**
 * Copyright (c) 2026, Adrien Devresse <adev@adev.name>
 *
 * Boost Software License - Version 1.0
 *
 * Permission is hereby granted, free of charge, to any person or organization
 * obtaining a copy of the software and accompanying documentation covered by
 * this license (the "Software") to use, reproduce, display, distribute,
 * execute, and transmit the Software, and to prepare derivative works of the
 * Software, and to permit third-parties to whom the Software is furnished to
 * do so, all subject to the following:
 *
 * The copyright notices in the Software and this entire statement, including
 * the above license grant, this restriction and the following disclaimer,
 * must be included in all copies of the Software, in whole or in part, and
 * all derivative works of the Software, unless such copies or derivative
 * works are solely in the form of machine-executable object code generated by
 * a source language processor.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
 * SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE
 * FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
 * ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
 * DEALINGS IN THE SOFTWARE.
 *
 */

#define DOCTEST_CONFIG_IMPLEMENT_WITH_MAIN
#include "doctest/doctest.h"

#include <cstdint>
#include <limits>
#include <random>
#include <sstream>
#include <type_traits>

#include "alea/random.hpp"

//
// the threefry generators must be usable in constant expressions: this also
// checks at compile time that the cipher is deterministic and stateless
//

static_assert(alea::threefry4x64{}(alea::threefry4x64::domain_type{1, 2, 3, 4})[0] == 14276687134489684560ULL);
static_assert(alea::threefry2x32{}(alea::threefry2x32::domain_type{1, 2})[1] == 3131650755U);

TEST_CASE("threefry golden values, 32 bits") {
  SUBCASE("threefry2x32") {
    alea::threefry2x32 cipher;
    const auto block = cipher(alea::threefry2x32::domain_type{1, 2});
    CHECK_EQ(block[0], 1390163619U);
    CHECK_EQ(block[1], 3131650755U);
    static_assert(std::is_same_v<alea::threefry2x32::uint_type, std::uint32_t>, "threefry2x32 must use 32 bit words");
  }

  SUBCASE("threefry4x32") {
    alea::threefry4x32 cipher;
    const auto block = cipher(alea::threefry4x32::domain_type{1, 2, 3, 4});
    CHECK_EQ(block[0], 3493051854U);
    CHECK_EQ(block[1], 2581483932U);
    CHECK_EQ(block[2], 998428297U);
    CHECK_EQ(block[3], 2429851283U);
  }
}

TEST_CASE("threefry golden values, 64 bits") {
  SUBCASE("threefry2x64") {
    alea::threefry2x64 cipher;
    const auto block = cipher(alea::threefry2x64::domain_type{1, 2});
    CHECK_EQ(block[0], 3797989197207778043ULL);
    CHECK_EQ(block[1], 9805594228365740645ULL);
  }

  SUBCASE("threefry4x64") {
    alea::threefry4x64 cipher;
    const auto block = cipher(alea::threefry4x64::domain_type{1, 2, 3, 4});
    CHECK_EQ(block[0], 14276687134489684560ULL);
    CHECK_EQ(block[1], 12958816754744280892ULL);
    CHECK_EQ(block[2], 17894100595138145301ULL);
    CHECK_EQ(block[3], 1013103230217800475ULL);
  }

  SUBCASE("threefry_default is threefry4x64") {
    static_assert(std::is_same_v<alea::threefry_default, alea::threefry4x64>,
                  "the default generator must be threefry4x64");
    static_assert(std::is_same_v<alea::threefry_default::uint_type, std::uint64_t>,
                  "the default generator must use 64 bit words");
    CHECK(true);
  }
}

TEST_CASE("counter_engine golden stream, 32 bits") {
  alea::counter_engine<alea::threefry2x32> engine;
  std::uint64_t val = 0;

  for (int i = 0; i <= 1000; ++i) {
    val = engine();
    if (i == 0) {
      CHECK_EQ(val, 3235790642U);
    } else if (i == 10) {
      CHECK_EQ(val, 2882477498U);
    } else if (i == 100) {
      CHECK_EQ(val, 1065648981U);
    } else if (i == 1000) {
      CHECK_EQ(val, 2548131963U);
    }
  }
}

TEST_CASE("counter_engine golden stream, 64 bits") {
  alea::counter_engine<alea::threefry4x64> engine;
  std::uint64_t val = 0;

  // these values are the ones of the reference Random123 threefry4x64 stream
  for (int i = 0; i <= 1000; ++i) {
    val = engine();
    if (i == 0) {
      CHECK_EQ(val, 12180738260140386403ULL);
    } else if (i == 10) {
      CHECK_EQ(val, 15340443714481834838ULL);
    } else if (i == 100) {
      CHECK_EQ(val, 6790623761552653118ULL);
    } else if (i == 1000) {
      CHECK_EQ(val, 16214960538048011ULL);
    }
  }
}

TEST_CASE_TEMPLATE("threefry api", Cbrng, alea::threefry2x32, alea::threefry4x32, alea::threefry2x64,
                   alea::threefry4x64) {
  using uint_type = typename Cbrng::uint_type;
  using key_type = typename Cbrng::key_type;
  using domain_type = typename Cbrng::domain_type;

  CHECK_EQ(Cbrng::number_of_rounds, 20U);

  // the default key is made of zeros, and the generator is stateless
  Cbrng default_cipher;
  CHECK_EQ(default_cipher.get_key(), key_type{});

  domain_type counter{};
  for (std::size_t i = 0; i < counter.size(); ++i) {
    counter[i] = static_cast<uint_type>(i + 1);
  }

  const auto first = default_cipher(counter);
  const auto second = default_cipher(counter);
  CHECK_EQ(first, second);

  // the key must be readable and updatable
  key_type key{};
  for (std::size_t i = 0; i < key.size(); ++i) {
    key[i] = static_cast<uint_type>(0x0123456789ABCDEFULL);
  }
  default_cipher.set_key(key);
  CHECK_EQ(default_cipher.get_key(), key);

  SUBCASE("equality is only based on the key") {
    Cbrng other(key);
    CHECK(default_cipher == other);
    CHECK_FALSE(default_cipher != other);

    other.set_key(key_type{});
    CHECK(default_cipher != other);
    CHECK_FALSE(default_cipher == other);
  }

  SUBCASE("different keys give different blocks") {
    const auto with_key = default_cipher(counter);
    const Cbrng cipher_zero_key;
    const auto without_key = cipher_zero_key(counter);

    std::size_t different_words = 0;
    for (std::size_t i = 0; i < with_key.size(); ++i) {
      different_words += (with_key[i] != without_key[i]) ? 1 : 0;
    }
    CHECK_GT(different_words, 0);
  }

  SUBCASE("ciphers are copy and move constructible") {
    const Cbrng copy(default_cipher);
    const Cbrng moved(default_cipher);
    CHECK(copy == default_cipher);
    CHECK(moved == default_cipher);
    CHECK_EQ(copy(counter), default_cipher(counter));
  }
}

TEST_CASE_TEMPLATE("counter_engine api", Cbrng, alea::threefry2x32, alea::threefry4x32, alea::threefry2x64,
                   alea::threefry4x64) {
  using engine_type = alea::counter_engine<Cbrng>;
  using result_type = typename engine_type::result_type;
  using key_type = typename engine_type::key_type;
  using ctr_type = typename engine_type::ctr_type;

  // engine requirements
  static_assert(std::is_unsigned_v<result_type>, "the result type must be unsigned");
  CHECK_EQ(engine_type::min(), static_cast<result_type>(0));
  CHECK_EQ(engine_type::max(), std::numeric_limits<result_type>::max());

  key_type key{};
  for (std::size_t i = 0; i < key.size(); ++i) {
    key[i] = static_cast<result_type>(i + 42);
  }

  SUBCASE("two engines with the same key give the same stream") {
    engine_type first(key);
    engine_type second;
    second.seed(key);

    for (int i = 0; i < 1000; ++i) {
      CHECK_EQ(first(), second());
    }
    CHECK(first == second);
    CHECK_FALSE(first != second);
  }

  SUBCASE("two engines with different keys give independent streams") {
    engine_type first(key);
    key_type other_key = key;
    other_key[0] = static_cast<result_type>(other_key[0] + 1);
    engine_type second(other_key);

    std::size_t identical_values = 0;
    for (int i = 0; i < 1000; ++i) {
      identical_values += (first() == second()) ? 1 : 0;
    }
    CHECK_EQ(identical_values, 0);
  }

  SUBCASE("seed and get_key, get_counter") {
    engine_type engine;
    CHECK_EQ(engine.get_key(), key_type{});
    CHECK_EQ(engine.get_counter(), ctr_type{});

    engine.seed(key);
    CHECK_EQ(engine.get_key(), key);

    engine.seed(static_cast<result_type>(1234));
    key_type broadcasted{};
    for (result_type& val : broadcasted) {
      val = static_cast<result_type>(1234);
    }
    CHECK_EQ(engine.get_key(), broadcasted);

    std::seed_seq seq{1, 2, 3, 4, 5, 6};
    engine_type from_seq(seq);
    CHECK_NE(engine.get_key(), from_seq.get_key());

    // the counter moves forward once the whole block has been consumed
    engine_type stepper(key);
    const std::size_t block_size = stepper.get_counter().size();
    for (std::size_t i = 0; i < block_size; ++i) {
      (void)stepper();
    }
    CHECK_EQ(stepper.get_counter(), ctr_type{1});
  }

  SUBCASE("generate_block is the encryption of the incremented counter") {
    engine_type engine(key);
    const Cbrng cipher(key);
    const ctr_type block = engine.generate_block();

    ctr_type expected_ctr{};
    expected_ctr[0] = 1;
    CHECK_EQ(block, cipher(expected_ctr));
    CHECK_EQ(engine.get_counter(), expected_ctr);
  }

  SUBCASE("operator() on a counter is a pure encryption") {
    const engine_type engine(key);
    ctr_type counter{};
    for (std::size_t i = 0; i < counter.size(); ++i) {
      counter[i] = static_cast<result_type>(7);
    }

    const Cbrng cipher(key);
    CHECK_EQ(engine(counter), cipher(counter));
    // the state of the engine is left untouched
    CHECK_EQ(engine.get_counter(), ctr_type{});
  }

  SUBCASE("discard is consistent with consuming one by one") {
    // discard(0) leaves the engine untouched
    {
      engine_type engine(key);
      engine_type clone(key);
      clone.discard(0);
      CHECK_EQ(engine(), clone());
    }

    // a number of values divisible by the block size
    {
      engine_type engine(key);
      engine_type clone(key);
      for (int i = 0; i < 100; ++i) {
        (void)engine();
      }
      clone.discard(100);
      CHECK_EQ(engine(), clone());
    }

    // a prime number of values, not divisible by the block size
    {
      engine_type engine(key);
      engine_type clone(key);
      const std::size_t inc_n = 1181;
      for (std::size_t i = 0; i < inc_n; ++i) {
        (void)engine();
      }
      clone.discard(inc_n);
      CHECK_EQ(engine(), clone());
    }

    // discarding inside the currently buffered block
    {
      engine_type engine(key);
      engine_type clone(key);
      (void)engine();
      clone.discard(1);
      CHECK_EQ(engine(), clone());
    }
  }

  SUBCASE("discard supports increments larger than a 32 bit word") {
    engine_type engine(key);
    engine_type clone(key);

    const std::uintmax_t max_val = std::numeric_limits<std::uintmax_t>::max();
    const std::size_t factor = 50;
    const std::uintmax_t small_inc = max_val / 16 / factor;
    const std::uintmax_t big_inc = small_inc * factor;

    for (std::size_t i = 0; i < factor; ++i) {
      engine.discard(small_inc);
    }
    clone.discard(big_inc);

    CHECK_EQ(engine.get_counter(), clone.get_counter());
    CHECK_EQ(engine(), clone());
  }

  SUBCASE("engines are copy constructible and stream printable") {
    engine_type engine(key);
    for (int i = 0; i < 3; ++i) {
      (void)engine();
    }

    const engine_type copy(engine);
    CHECK(copy == engine);

    std::ostringstream os;
    os << engine;
    CHECK_FALSE(os.str().empty());
  }

  SUBCASE("the engine is usable with the std distributions") {
    std::uniform_int_distribution<result_type> int_dist(0, 100);
    std::uniform_real_distribution<double> real_dist(0.0, 1.0);

    engine_type engine(key);
    std::uint64_t sum = 0;
    const std::size_t n_normalize = 100000;

    for (std::size_t i = 0; i < n_normalize; ++i) {
      const result_type val = int_dist(engine);
      CHECK_GE(val, static_cast<result_type>(0));
      CHECK_LE(val, static_cast<result_type>(100));
      sum += val;

      const double dval = real_dist(engine);
      CHECK_GE(dval, 0.0);
      CHECK_LE(dval, 1.0);
    }

    const std::uint64_t mean = sum / n_normalize;
    CHECK_GE(mean, 49);
    CHECK_LE(mean, 51);
  }
}
