/**
 * Copyright (c) 2026, Adrien Devresse <adev@adev.name>
 *
 * Boost Software License - Version 1.0
 *
 * Permission is hereby granted, free of charge, to any person or organization
 * obtaining a copy of the software and accompanying documentation covered by
 * this license (the "Software") to use, reproduce, display, distribute,
 * execute, and transmit the Software, and to prepare derivative works of the
 * Software, and to permit third-parties to whom the Software is furnished to
 * do so, all subject to the following:
 *
 * The copyright notices in the Software and this entire statement, including
 * the above license grant, this restriction and the following disclaimer,
 * must be included in all copies of the Software, in whole or in part, and
 * all derivative works of the Software, unless such copies or derivative
 * works are solely in the form of machine-executable object code generated by
 * a source language processor.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
 * SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE
 * FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
 * ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
 * DEALINGS IN THE SOFTWARE.
 *
 */
#pragma once

#include <array>
#include <cstdint>

#include "alea/gpu_portability.hpp"
#include "alea/impl/ars_impl.hpp"

//
// This work is derivated from the Random123 repository available here
// https://github.com/DEShawResearch/random123
//

namespace alea {

/// ars is a state-less counter based random generator built around the AES
/// round function with a simplified key schedule, the Advanced Randomization
/// System of Random123.
///
/// ars has been presented at SC11 in the publication
///   "Parallel random numbers: as easy as 1, 2, 3".
///    John K. Salmon, Mark A. Moraes, Ron O. Dror, David E. Shaw
///    (doi:10.1145/2063384.2063405)
///
/// Unlike threefry and philox, the ARS bijection is exactly the AES round
/// function (SubBytes, ShiftRows, MixColumns, AddRoundKey): only the key
/// schedule is replaced by a Weyl sequence, which makes the generator
/// Crush-resistant but not cryptographically secure. On x86 and AArch64 CPUs
/// the round is a single hardware instruction, which makes ARS the fastest
/// Crush-resistant generator of the family on those platforms.
///
/// This implementation is freely inspired by Random123
/// (https://github.com/DEShawResearch/random123)
///
/// \tparam R number of rounds of the AES round function, 7 by default, the
///         value used by the reference implementation
template <unsigned R = 7> class ars {
  static_assert(R >= 1, "an ARS generator must perform at least one round");

public:
  using domain_type = std::array<std::uint32_t, 4>;
  using range_type = std::array<std::uint32_t, 4>;
  using key_type = std::array<std::uint32_t, 4>;
  using uint_type = std::uint32_t;

  /// number of rounds performed by the generator
  static constexpr unsigned number_of_rounds = R;

  /// construct a generator with a key set to zero
  ALEA_HOST_DEVICE constexpr ars() : k() {}

  /// construct a generator with the key `new_key`
  ALEA_HOST_DEVICE explicit constexpr ars(key_type new_key) : k(new_key) {}

  constexpr ars(const ars&) = default;
  constexpr ars(ars&&) = default;

  ars& operator=(const ars&) = default;
  ars& operator=(ars&&) = default;

  /// set the key of the generator
  ALEA_HOST_DEVICE void set_key(key_type new_key) { k = new_key; }

  /// get the key of the generator
  ALEA_HOST_DEVICE key_type get_key() const { return k; }

  ALEA_HOST_DEVICE bool operator==(const ars& rhs) const { return k == rhs.k; }

  ALEA_HOST_DEVICE bool operator!=(const ars& rhs) const { return k != rhs.k; }

  /// encrypt the counter `counter` with the current key of the generator
  ///
  /// the operation is stateless: the same (key, counter) pair always produces
  /// the same block, whatever the number of times and the order of the calls.
  ALEA_HOST_DEVICE constexpr range_type operator()(const domain_type& counter) const {
    return impl::ars_encrypt<R>(counter, k);
  }

private:
  key_type k;
};

/// ARS works on a single 128 bit block, i.e. on four 32 bit words: the
/// reference implementation exposes it as ARS4x32
using ars4x32 = ars<7>;

/// with 7 rounds, ARS has a considerable safety margin over the 5 rounds
/// needed to pass Crush, and is the recommended default of the family
using ars_default = ars4x32;

} // namespace alea
