/**
 * Copyright (c) 2026, Adrien Devresse <adev@adev.name>
 *
 * Boost Software License - Version 1.0
 *
 * Permission is hereby granted, free of charge, to any person or organization
 * obtaining a copy of the software and accompanying documentation covered by
 * this license (the "Software") to use, reproduce, display, distribute,
 * execute, and transmit the Software, and to prepare derivative works of the
 * Software, and to permit third-parties to whom the Software is furnished to
 * do so, all subject to the following:
 *
 * The copyright notices in the Software and this entire statement, including
 * the above license grant, this restriction and the following disclaimer,
 * must be included in all copies of the Software, in whole or in part, and
 * all derivative works of the Software, unless such copies or derivative
 * works are solely in the form of machine-executable object code generated by
 * a source language processor.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
 * SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE
 * FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
 * ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
 * DEALINGS IN THE SOFTWARE.
 *
 */
#pragma once

#include <array>
#include <cstddef>
#include <cstdint>
#include <limits>
#include <span>

//
// BLAKE2b and BLAKE2s as specified in RFC 7693, in their unkeyed, fixed
// digest length variants (BLAKE2b-512 and BLAKE2s-256).
//
// This is a direct implementation of the specification and of the reference C
// implementation published by the BLAKE2 authors
// (https://github.com/BLAKE2/BLAKE2, ref/blake2b-ref.c and
// ref/blake2s-ref.c). The tests validate the two implementations bit to bit
// against that reference when -DALEA_ENABLE_VALIDATION_BLAKE2=ON.
//
// The hashers are plain value structs with an inline state, no dynamic
// allocation and no virtual member: a hasher can be copied, moved, kept on
// the stack or stored in an array. They are also usable during constant
// evaluation.
//

namespace alea {
namespace impl {

/// rotate the bits of `value` to the right by `bits` positions
template <typename uint_type> constexpr uint_type rotr(uint_type value, unsigned int bits) noexcept {
  return static_cast<uint_type>((value >> bits) | (value << (std::numeric_limits<uint_type>::digits - bits)));
}

/// load an unsigned integer stored in little endian order
template <typename uint_type> constexpr uint_type load_le(const std::byte* bytes) noexcept {
  uint_type value = 0;
  for (std::size_t i = 0; i < sizeof(uint_type); ++i) {
    value |= static_cast<uint_type>(std::to_integer<unsigned int>(bytes[i])) << (8u * i);
  }
  return value;
}

/// store an unsigned integer in little endian order
template <typename uint_type> constexpr void store_le(std::byte* bytes, uint_type value) noexcept {
  for (std::size_t i = 0; i < sizeof(uint_type); ++i) {
    bytes[i] = static_cast<std::byte>((value >> (8u * i)) & static_cast<uint_type>(0xff));
  }
}

/// message word permutation shared by BLAKE2b and BLAKE2s. Both algorithms
/// use the same ten permutations, BLAKE2b simply repeats the first two of
/// them for its last two rounds.
inline constexpr std::uint8_t blake2_sigma[10][16] = {
    {0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15}, {14, 10, 4, 8, 9, 15, 13, 6, 1, 12, 0, 2, 11, 7, 5, 3},
    {11, 8, 12, 0, 5, 2, 15, 13, 10, 14, 3, 6, 7, 1, 9, 4}, {7, 9, 3, 1, 13, 12, 11, 14, 2, 6, 5, 10, 4, 0, 15, 8},
    {9, 0, 5, 7, 2, 4, 10, 15, 14, 1, 11, 12, 6, 8, 3, 13}, {2, 12, 6, 10, 0, 11, 8, 3, 4, 13, 7, 5, 15, 14, 1, 9},
    {12, 5, 1, 15, 14, 13, 4, 10, 0, 7, 6, 3, 9, 2, 8, 11}, {13, 11, 7, 14, 12, 1, 3, 9, 5, 0, 15, 4, 8, 6, 2, 10},
    {6, 15, 14, 9, 11, 3, 0, 8, 12, 2, 13, 7, 1, 4, 10, 5}, {10, 2, 8, 4, 7, 6, 1, 5, 15, 11, 9, 14, 3, 12, 13, 0},
};

/// initialisation vectors of BLAKE2b, shared with SHA-512
inline constexpr std::array<std::uint64_t, 8> blake2b_iv = {
    0x6a09e667f3bcc908ull, 0xbb67ae8584caa73bull, 0x3c6ef372fe94f82bull, 0xa54ff53a5f1d36f1ull,
    0x510e527fade682d1ull, 0x9b05688c2b3e6c1full, 0x1f83d9abfb41bd6bull, 0x5be0cd19137e2179ull,
};

/// initialisation vectors of BLAKE2s, shared with SHA-256
inline constexpr std::array<std::uint32_t, 8> blake2s_iv = {
    0x6a09e667u, 0xbb67ae85u, 0x3c6ef372u, 0xa54ff53au, 0x510e527fu, 0x9b05688cu, 0x1f83d9abu, 0x5be0cd19u,
};

/// initial chaining value of unkeyed BLAKE2b-512: the first IV word is XORed
/// with the parameter block 0x01010000 | (key_length << 8) | digest_length
constexpr std::array<std::uint64_t, 8> blake2b_initial_state() noexcept {
  std::array<std::uint64_t, 8> state = blake2b_iv;
  state[0] ^= 0x01010000ull | 0x40ull;
  return state;
}

/// initial chaining value of unkeyed BLAKE2s-256
constexpr std::array<std::uint32_t, 8> blake2s_initial_state() noexcept {
  std::array<std::uint32_t, 8> state = blake2s_iv;
  state[0] ^= 0x01010000u | 0x20u;
  return state;
}

/// the BLAKE2b mixing function G
constexpr void blake2b_mix(std::array<std::uint64_t, 16>& v, unsigned int a, unsigned int b, unsigned int c,
                           unsigned int d, std::uint64_t x, std::uint64_t y) noexcept {
  v[a] = v[a] + v[b] + x;
  v[d] = rotr(v[d] ^ v[a], 32u);
  v[c] = v[c] + v[d];
  v[b] = rotr(v[b] ^ v[c], 24u);
  v[a] = v[a] + v[b] + y;
  v[d] = rotr(v[d] ^ v[a], 16u);
  v[c] = v[c] + v[d];
  v[b] = rotr(v[b] ^ v[c], 63u);
}

/// the BLAKE2s mixing function G
constexpr void blake2s_mix(std::array<std::uint32_t, 16>& v, unsigned int a, unsigned int b, unsigned int c,
                           unsigned int d, std::uint32_t x, std::uint32_t y) noexcept {
  v[a] = v[a] + v[b] + x;
  v[d] = rotr(v[d] ^ v[a], 16u);
  v[c] = v[c] + v[d];
  v[b] = rotr(v[b] ^ v[c], 12u);
  v[a] = v[a] + v[b] + y;
  v[d] = rotr(v[d] ^ v[a], 8u);
  v[c] = v[c] + v[d];
  v[b] = rotr(v[b] ^ v[c], 7u);
}

/// the BLAKE2b compression function over a single 128 byte block
constexpr void blake2b_compress(std::array<std::uint64_t, 8>& h, const std::byte* block, std::uint64_t t0,
                                std::uint64_t t1, bool last) noexcept {
  std::array<std::uint64_t, 16> m{};
  for (std::size_t i = 0; i < 16; ++i) {
    m[i] = load_le<std::uint64_t>(block + i * 8);
  }

  std::array<std::uint64_t, 16> v{};
  for (std::size_t i = 0; i < 8; ++i) {
    v[i] = h[i];
    v[i + 8] = blake2b_iv[i];
  }
  v[12] ^= t0;
  v[13] ^= t1;
  if (last) {
    v[14] = ~v[14];
  }

  for (unsigned int r = 0; r < 12; ++r) {
    const std::uint8_t* s = blake2_sigma[r % 10];
    blake2b_mix(v, 0, 4, 8, 12, m[s[0]], m[s[1]]);
    blake2b_mix(v, 1, 5, 9, 13, m[s[2]], m[s[3]]);
    blake2b_mix(v, 2, 6, 10, 14, m[s[4]], m[s[5]]);
    blake2b_mix(v, 3, 7, 11, 15, m[s[6]], m[s[7]]);
    blake2b_mix(v, 0, 5, 10, 15, m[s[8]], m[s[9]]);
    blake2b_mix(v, 1, 6, 11, 12, m[s[10]], m[s[11]]);
    blake2b_mix(v, 2, 7, 8, 13, m[s[12]], m[s[13]]);
    blake2b_mix(v, 3, 4, 9, 14, m[s[14]], m[s[15]]);
  }

  for (std::size_t i = 0; i < 8; ++i) {
    h[i] ^= v[i] ^ v[i + 8];
  }
}

/// the BLAKE2s compression function over a single 64 byte block
constexpr void blake2s_compress(std::array<std::uint32_t, 8>& h, const std::byte* block, std::uint32_t t0,
                                std::uint32_t t1, bool last) noexcept {
  std::array<std::uint32_t, 16> m{};
  for (std::size_t i = 0; i < 16; ++i) {
    m[i] = load_le<std::uint32_t>(block + i * 4);
  }

  std::array<std::uint32_t, 16> v{};
  for (std::size_t i = 0; i < 8; ++i) {
    v[i] = h[i];
    v[i + 8] = blake2s_iv[i];
  }
  v[12] ^= t0;
  v[13] ^= t1;
  if (last) {
    v[14] = ~v[14];
  }

  for (unsigned int r = 0; r < 10; ++r) {
    const std::uint8_t* s = blake2_sigma[r];
    blake2s_mix(v, 0, 4, 8, 12, m[s[0]], m[s[1]]);
    blake2s_mix(v, 1, 5, 9, 13, m[s[2]], m[s[3]]);
    blake2s_mix(v, 2, 6, 10, 14, m[s[4]], m[s[5]]);
    blake2s_mix(v, 3, 7, 11, 15, m[s[6]], m[s[7]]);
    blake2s_mix(v, 0, 5, 10, 15, m[s[8]], m[s[9]]);
    blake2s_mix(v, 1, 6, 11, 12, m[s[10]], m[s[11]]);
    blake2s_mix(v, 2, 7, 8, 13, m[s[12]], m[s[13]]);
    blake2s_mix(v, 3, 4, 9, 14, m[s[14]], m[s[15]]);
  }

  for (std::size_t i = 0; i < 8; ++i) {
    h[i] ^= v[i] ^ v[i + 8];
  }
}

} // namespace impl

/// BLAKE2b with a 64 byte digest (BLAKE2b-512), unkeyed
struct blake2b {
  /// size in bytes of the digest returned by finalize()
  static constexpr std::size_t digest_size = 64;
  /// size in bytes of the blocks processed by the compression function
  static constexpr std::size_t block_size = 128;
  /// type returned by finalize()
  using digest_type = std::array<std::byte, digest_size>;

  /// chaining value, initialised for the unkeyed BLAKE2b-512
  std::array<std::uint64_t, 8> h = impl::blake2b_initial_state();
  /// bytes not yet compressed, always fewer than block_size
  std::array<std::byte, block_size> buffer = {};
  /// number of valid bytes in buffer
  std::size_t buffer_used = 0;
  /// number of message bytes already fed to the compression function
  std::uint64_t counter = 0;

  /// bring the hasher back to its initial state, all the members are reset
  constexpr void reset() noexcept {
    h = impl::blake2b_initial_state();
    buffer_used = 0;
    counter = 0;
  }

  /// absorb a chunk of the message
  constexpr void update(std::span<const std::byte> data) noexcept {
    const std::byte* input = data.data();
    std::size_t remaining = data.size();

    while (remaining != 0) {
      // a full buffer is only compressed once more input is available, so that
      // the last block of the message is always the one compressed by finalize()
      if (buffer_used == block_size) {
        counter += block_size;
        impl::blake2b_compress(h, buffer.data(), counter, 0, false);
        buffer_used = 0;
      }

      const std::size_t space = block_size - buffer_used;
      const std::size_t to_copy = (space < remaining) ? space : remaining;
      for (std::size_t i = 0; i < to_copy; ++i) {
        buffer[buffer_used + i] = input[i];
      }
      buffer_used += to_copy;
      input += to_copy;
      remaining -= to_copy;
    }
  }

  /// return the BLAKE2b-512 digest of everything absorbed so far, the hasher
  /// is left in a usable but unspecified state
  constexpr digest_type finalize() noexcept {
    std::array<std::byte, block_size> last_block = {};
    for (std::size_t i = 0; i < buffer_used; ++i) {
      last_block[i] = buffer[i];
    }

    counter += buffer_used;
    impl::blake2b_compress(h, last_block.data(), counter, 0, true);

    digest_type digest{};
    for (std::size_t i = 0; i < 8; ++i) {
      impl::store_le(digest.data() + i * 8, h[i]);
    }
    return digest;
  }
};

/// BLAKE2s with a 32 byte digest (BLAKE2s-256), unkeyed
struct blake2s {
  /// size in bytes of the digest returned by finalize()
  static constexpr std::size_t digest_size = 32;
  /// size in bytes of the blocks processed by the compression function
  static constexpr std::size_t block_size = 64;
  /// type returned by finalize()
  using digest_type = std::array<std::byte, digest_size>;

  /// chaining value, initialised for the unkeyed BLAKE2s-256
  std::array<std::uint32_t, 8> h = impl::blake2s_initial_state();
  /// bytes not yet compressed, always fewer than block_size
  std::array<std::byte, block_size> buffer = {};
  /// number of valid bytes in buffer
  std::size_t buffer_used = 0;
  /// number of message bytes already fed to the compression function
  std::uint64_t counter = 0;

  /// bring the hasher back to its initial state, all the members are reset
  constexpr void reset() noexcept {
    h = impl::blake2s_initial_state();
    buffer_used = 0;
    counter = 0;
  }

  /// absorb a chunk of the message
  constexpr void update(std::span<const std::byte> data) noexcept {
    const std::byte* input = data.data();
    std::size_t remaining = data.size();

    while (remaining != 0) {
      // a full buffer is only compressed once more input is available, so that
      // the last block of the message is always the one compressed by finalize()
      if (buffer_used == block_size) {
        counter += block_size;
        impl::blake2s_compress(h, buffer.data(), static_cast<std::uint32_t>(counter),
                               static_cast<std::uint32_t>(counter >> 32), false);
        buffer_used = 0;
      }

      const std::size_t space = block_size - buffer_used;
      const std::size_t to_copy = (space < remaining) ? space : remaining;
      for (std::size_t i = 0; i < to_copy; ++i) {
        buffer[buffer_used + i] = input[i];
      }
      buffer_used += to_copy;
      input += to_copy;
      remaining -= to_copy;
    }
  }

  /// return the BLAKE2s-256 digest of everything absorbed so far, the hasher
  /// is left in a usable but unspecified state
  constexpr digest_type finalize() noexcept {
    std::array<std::byte, block_size> last_block = {};
    for (std::size_t i = 0; i < buffer_used; ++i) {
      last_block[i] = buffer[i];
    }

    counter += buffer_used;
    impl::blake2s_compress(h, last_block.data(), static_cast<std::uint32_t>(counter),
                           static_cast<std::uint32_t>(counter >> 32), true);

    digest_type digest{};
    for (std::size_t i = 0; i < 8; ++i) {
      impl::store_le(digest.data() + i * 4, h[i]);
    }
    return digest;
  }
};

} // namespace alea
