/**
 * Copyright (c) 2026, Adrien Devresse <adev@adev.name>
 *
 * Boost Software License - Version 1.0
 *
 * Permission is hereby granted, free of charge, to any person or organization
 * obtaining a copy of the software and accompanying documentation covered by
 * this license (the "Software") to use, reproduce, display, distribute,
 * execute, and transmit the Software, and to prepare derivative works of the
 * Software, and to permit third-parties to whom the Software is furnished to
 * do so, all subject to the following:
 *
 * The copyright notices in the Software and this entire statement, including
 * the above license grant, this restriction and the following disclaimer,
 * must be included in all copies of the Software, in whole or in part, and
 * all derivative works of the Software, unless such copies or derivative
 * works are solely in the form of machine-executable object code generated by
 * a source language processor.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
 * SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE
 * FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
 * ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
 * DEALINGS IN THE SOFTWARE.
 *
 */
#pragma once

#include <array>
#include <cstddef>
#include <cstdint>
#include <limits>
#include <ostream>
#include <random>
#include <type_traits>

#include "alea/threefry.hpp"

//
// This work is inspired by the algorithms presented in the publication
//   "Parallel random numbers: as easy as 1, 2, 3".
//     John K. Salmon, Mark A. Moraes, Ron O. Dror, David E. Shaw
//     (doi:10.1145/2063384.2063405)
//
// It is freely inspired by Boost.Random123
// (https://github.com/DEShawResearch/Random123-Boost) and by the original
// Random123 package distribution.
//

namespace alea {

/// counter_engine adapts a counter based random generator (CBRNG) into an
/// engine satisfying the C++11 random engine requirements, and therefore
/// usable with all the `std::` distributions.
///
/// The engine owns a key (the identifier of the "stream") and a counter. Two
/// engines with different keys produce statistically independent streams, and
/// two engines with the same key produce the same stream, whatever the thread
/// or the process they belong to. The counter can be moved forward with
/// `discard()`, which makes it cheap to split a stream between workers without
/// any communication.
///
/// \tparam CBRNG a counter based random generator, for example `threefry4x64`
template <typename CBRNG> class counter_engine {
  static_assert(std::is_unsigned_v<typename CBRNG::uint_type>, "the words of a CBRNG counter must be unsigned");

public:
  using cbrng_type = CBRNG;
  using ctr_type = typename CBRNG::domain_type;
  using key_type = typename CBRNG::key_type;
  using result_type = typename ctr_type::value_type;
  using elem_type = std::size_t;

  /// construct an engine with a zeroed key and a zeroed counter
  constexpr counter_engine() : b(), c(), elem(), v() {}

  /// construct an engine using the key `uk` and a zeroed counter
  explicit constexpr counter_engine(const key_type& uk) : b(uk), c(), elem(), v() {}

  /// construct an engine with the key broadcasted from the seed `r`
  explicit constexpr counter_engine(result_type r) : b(broadcast_key(r)), c(), elem(), v() {}

  /// construct an engine with a key generated from the seed sequence `seq`
  explicit counter_engine(std::seed_seq& seq) : b(seed_key(seq)), c(), elem(), v() {}

  constexpr counter_engine(const counter_engine&) = default;
  constexpr counter_engine(counter_engine&&) = default;

  counter_engine& operator=(const counter_engine&) = default;
  counter_engine& operator=(counter_engine&&) = default;

  /// reset the engine to the default state: zeroed key and zeroed counter
  void seed() { *this = counter_engine(); }

  /// reset the engine to the key broadcasted from the seed `r`
  void seed(result_type r) { *this = counter_engine(r); }

  /// reset the engine to the key `uk`
  void seed(const key_type& uk) { *this = counter_engine(uk); }

  /// reset the engine to a key generated from the seed sequence `seq`
  void seed(std::seed_seq& seq) {
    b.set_key(seed_key(seq));
    c = ctr_type();
    elem = 0;
    v = ctr_type();
  }

  friend bool operator==(const counter_engine& lhs, const counter_engine& rhs) {
    return lhs.b == rhs.b && lhs.c == rhs.c && lhs.elem == rhs.elem;
  }

  friend bool operator!=(const counter_engine& lhs, const counter_engine& rhs) { return !(lhs == rhs); }

  /// write the state of the engine (counter, key and number of buffered
  /// values) to the stream `os`
  friend std::ostream& operator<<(std::ostream& os, const counter_engine& be) {
    for (const result_type val : be.c) {
      os << val << ' ';
    }
    for (const result_type val : be.b.get_key()) {
      os << val << ' ';
    }
    return os << be.elem;
  }

  /// minimum value returned by the engine
  static constexpr result_type min() { return 0; }

  /// maximum value returned by the engine
  static constexpr result_type max() { return std::numeric_limits<result_type>::max(); }

  /// return the next value of the stream
  ///
  /// the counter is incremented and encrypted by the CBRNG once every
  /// `ctr_type::size()` calls, the generated block is buffered
  result_type operator()() {
    if (elem == 0) {
      incr_array(c.begin(), c.end());
      v = b(c);
      elem = c.size();
    }
    elem -= 1;
    return v[elem];
  }

  /// alias of `operator()`, kept for compatibility with legacy APIs
  result_type generate() { return (*this)(); }

  /// increment the counter and return the whole encrypted block
  ctr_type generate_block() {
    elem = 0;
    incr_array(c.begin(), c.end());
    v = b(c);
    return v;
  }

  /// move the stream forward by `skip` values without generating them one by
  /// one
  void discard(std::uintmax_t skip) {
    // the buffered values are dropped first
    while (elem != 0 && skip > 0) {
      skip -= 1;
      elem -= 1;
    }

    const elem_type nelem = c.size();
    const std::uintmax_t counter_increment = skip / nelem;
    std::uintmax_t counter_rest = skip % nelem;

    incr_array(c.begin(), c.end(), counter_increment);

    // then consume the remaining values of the last block
    while (counter_rest > 0) {
      (void)(*this)();
      counter_rest -= 1;
    }
  }

  /// return the CBRNG encryption of the counter `counter` with the current
  /// key, without modifying the state of the engine
  ctr_type operator()(const ctr_type& counter) const { return b(counter); }

  /// return the key of the engine, i.e. the identifier of its stream
  key_type get_key() const { return b.get_key(); }

  /// return the current counter of the engine
  ctr_type get_counter() const { return c; }

private:
  static constexpr key_type broadcast_key(result_type r) {
    key_type key{};
    for (result_type& val : key) {
      val = r;
    }
    return key;
  }

  static key_type seed_key(std::seed_seq& seq) {
    key_type key{};
    seq.generate(key.begin(), key.end());
    return key;
  }

  // increment by one the big integer represented by the array [start, finish)
  template <typename Iterator> static inline void incr_array(Iterator start, Iterator finish) {
    constexpr typename cbrng_type::uint_type max_elem = std::numeric_limits<typename cbrng_type::uint_type>::max();

    while (start != finish) {
      if (*start == max_elem) {
        *start = 0;
        start += 1;
      } else {
        *start += 1;
        break;
      }
    }
  }

  // increment by `inc_val` the big integer represented by [start, finish)
  template <typename Iterator> static void incr_array(Iterator start, Iterator finish, std::uintmax_t inc_val) {
    constexpr typename cbrng_type::uint_type max_elem = std::numeric_limits<typename cbrng_type::uint_type>::max();

    if (inc_val == 0 || start == finish) {
      return;
    }

    const std::uintmax_t current_inc_val = inc_val & max_elem;
    const std::uintmax_t next_inc_val =
        ((sizeof(std::uintmax_t) != sizeof(typename cbrng_type::uint_type)) ? (inc_val >> (sizeof(max_elem) * 8)) : 0);

    const typename cbrng_type::uint_type past_val = *start;
    *start += current_inc_val;

    if (*start < past_val) { // an overflow occurred, increment the next word
      incr_array(start + 1, finish, next_inc_val + 1);
    } else {
      incr_array(start + 1, finish, next_inc_val);
    }
  }

  cbrng_type b;
  ctr_type c;
  elem_type elem;
  ctr_type v;
};

} // namespace alea
