/**
 * Copyright (c) 2026, Adrien Devresse <adev@adev.name>
 *
 * Boost Software License - Version 1.0
 *
 * Permission is hereby granted, free of charge, to any person or organization
 * obtaining a copy of the software and accompanying documentation covered by
 * this license (the "Software") to use, reproduce, display, distribute,
 * execute, and transmit the Software, and to prepare derivative works of the
 * Software, and to permit third-parties to whom the Software is furnished to
 * do so, all subject to the following:
 *
 * The copyright notices in the Software and this entire statement, including
 * the above license grant, this restriction and the following disclaimer,
 * must be included in all copies of the Software, in whole or in part, and
 * all derivative works of the Software, unless such copies or derivative
 * works are solely in the form of machine-executable object code generated by
 * a source language processor.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
 * SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE
 * FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
 * ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
 * DEALINGS IN THE SOFTWARE.
 *
 */
#pragma once

//
// GPU portability layer of alea.
//
// alea is a single source library: the very same headers are compiled by a
// plain C++ compiler and by the CUDA compiler. The macros below expand to the
// CUDA execution space annotations when the headers are processed by nvcc and
// to nothing otherwise, so a function annotated ALEA_HOST_DEVICE is callable
// both from the host and from a CUDA kernel.
//
// A few standard library facilities used by alea (std::array,
// std::numeric_limits) are constexpr but host only: nvcc must be given
// `--expt-relaxed-constexpr` to call them from device code. The CMake CUDA
// targets of the project enable it automatically.
//

#if defined(__CUDACC__) || defined(__CUDA_ARCH__)
// compiled by nvcc: __host__ and __device__ are compiler builtins and do not
// require any CUDA header to be included
#define ALEA_HOST __host__
#define ALEA_DEVICE __device__
#define ALEA_HOST_DEVICE __host__ __device__
#else
// plain C++ compiler: no execution space annotation
#define ALEA_HOST
#define ALEA_DEVICE
#define ALEA_HOST_DEVICE
#endif