/**
 * Copyright (c) 2026, Adrien Devresse <adev@adev.name>
 *
 * Boost Software License - Version 1.0
 *
 * Permission is hereby granted, free of charge, to any person or organization
 * obtaining a copy of the software and accompanying documentation covered by
 * this license (the "Software") to use, reproduce, display, distribute,
 * execute, and transmit the Software, and to prepare derivative works of the
 * Software, and to permit third-parties to whom the Software is furnished to
 * do so, all subject to the following:
 *
 * The copyright notices in the Software and this entire statement, including
 * the above license grant, this restriction and the following disclaimer,
 * must be included in all copies of the Software, in whole or in part, and
 * all derivative works of the Software, unless such copies or derivative
 * works are solely in the form of machine-executable object code generated by
 * a source language processor.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
 * SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE
 * FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
 * ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
 * DEALINGS IN THE SOFTWARE.
 *
 */
#pragma once

#include <array>
#include <concepts>
#include <cstddef>
#include <span>

//
// The concept describing the interface shared by the cryptographic hashes of
// alea: blake2b, blake2s and sha256. It is the counterpart, for hashes, of
// the `cbrng` concept of random_concepts.hpp: generic code written against
// `hasher` can hash with any of the provided algorithms, and any conforming
// third party hash can be used transparently.
//

namespace alea {

/// `hasher` models an incremental cryptographic hash function.
///
/// A conforming hasher is a value type that can be default constructed in a
/// valid initial state, copied and moved. It exposes:
///   - `digest_size`, the size in bytes of the digest;
///   - `block_size`, the size in bytes of the blocks of the compression
///     function;
///   - `digest_type`, exactly `std::array<std::byte, digest_size>`, the type
///     returned by `finalize()`;
///   - `update(std::span<const std::byte>)`, to absorb a chunk of the
///     message, callable any number of times;
///   - `finalize()`, to produce the digest of everything absorbed so far and
///     return it as a `digest_type`;
///   - `reset()`, to bring the hasher back to its initial state.
///
/// Blake2b, blake2s and sha256 all satisfy this concept.
///
/// \tparam T the hasher type, for example `alea::blake2b`
template <typename T>
concept hasher =
    // a copyable, movable, default constructible and swappable value type
    std::semiregular<T> &&
    // the nested digest type and the compile time sizes of the algorithm
    requires {
      typename T::digest_type;
      { T::digest_size } -> std::convertible_to<std::size_t>;
      { T::block_size } -> std::convertible_to<std::size_t>;
    } &&
    // the digest type is a byte array whose length is the digest size
    std::same_as<typename T::digest_type, std::array<std::byte, T::digest_size>> &&
    // the incremental hashing interface
    requires(T h, std::span<const std::byte> data) {
      { h.update(data) } -> std::same_as<void>;
      { h.finalize() } -> std::same_as<typename T::digest_type>;
      { h.reset() } -> std::same_as<void>;
    };

} // namespace alea
