/**
 * Copyright (c) 2026, Adrien Devresse <adev@adev.name>
 *
 * Boost Software License - Version 1.0
 *
 * Permission is hereby granted, free of charge, to any person or organization
 * obtaining a copy of the software and accompanying documentation covered by
 * this license (the "Software") to use, reproduce, display, distribute,
 * execute, and transmit the Software, and to prepare derivative works of the
 * Software, and to permit third-parties to whom the Software is furnished to
 * do so, all subject to the following:
 *
 * The copyright notices in the Software and this entire statement, including
 * the above license grant, this restriction and the following disclaimer,
 * must be included in all copies of the Software, in whole or in part, and
 * all derivative works of the Software, unless such copies or derivative
 * works are solely in the form of machine-executable object code generated by
 * a source language processor.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
 * SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE
 * FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
 * ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
 * DEALINGS IN THE SOFTWARE.
 *
 */
#pragma once

#include <array>
#include <cstddef>
#include <iostream>
#include <ostream>
#include <string>

//
// Helpers to display an arbitrary digest, or any other array of std::byte,
// in lowercase hexadecimal form. They work with every hasher of alea since
// finalize() returns a std::array<std::byte, digest_size>.
//

namespace alea {

/// return the lowercase hexadecimal representation of an array of bytes
template <std::size_t N> std::string to_hex(const std::array<std::byte, N>& bytes) {
  constexpr char digits[] = "0123456789abcdef";
  std::string result;
  result.reserve(2 * N);
  for (const std::byte value : bytes) {
    const unsigned int byte = std::to_integer<unsigned int>(value);
    result.push_back(digits[(byte >> 4) & 0x0fu]);
    result.push_back(digits[byte & 0x0fu]);
  }
  return result;
}

/// print the lowercase hexadecimal representation of an array of bytes to an
/// output stream, followed by a newline unless `newline` is false
template <std::size_t N>
void print_hex(const std::array<std::byte, N>& bytes, std::ostream& out = std::cout, bool newline = true) {
  out << to_hex(bytes);
  if (newline) {
    out << '\n';
  }
}

} // namespace alea
