/**
 * Copyright (c) 2026, Adrien Devresse <adev@adev.name>
 *
 * Boost Software License - Version 1.0
 *
 * Permission is hereby granted, free of charge, to any person or organization
 * obtaining a copy of the software and accompanying documentation covered by
 * this license (the "Software") to use, reproduce, display, distribute,
 * execute, and transmit the Software, and to prepare derivative works of the
 * Software, and to permit third-parties to whom the Software is furnished to
 * do so, all subject to the following:
 *
 * The copyright notices in the Software and this entire statement, including
 * the above license grant, this restriction and the following disclaimer,
 * must be included in all copies of the Software, in whole or in part, and
 * all derivative works of the Software, unless such copies or derivative
 * works are solely in the form of machine-executable object code generated by
 * a source language processor.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
 * SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE
 * FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
 * ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
 * DEALINGS IN THE SOFTWARE.
 *
 */
#pragma once

#include <array>
#include <cstddef>
#include <cstdint>

#include "alea/gpu_portability.hpp"
#include "alea/impl/philox_impl.hpp"

//
// This work is derivated from the Boost.Random123 repository available here
// https://github.com/DEShawResearch/Random123-Boost
//

namespace alea {

/// philox is a state-less counter based random generator built around the
/// PHILOX (Product HI LO XOr) round function.
///
/// philox has been presented at SC11 in the publication
///   "Parallel random numbers: as easy as 1, 2, 3".
///    John K. Salmon, Mark A. Moraes, Ron O. Dror, David E. Shaw
///    (doi:10.1145/2063384.2063405)
///
/// Unlike threefry, a philox round is not built on additions and rotations
/// but on a wide integer multiplication, which makes it very fast on the
/// architectures that have a native 64x64 -> 128 bit multiply. It is
/// therefore the recommended generator when the widest word of the counter is
/// 64 bits.
///
/// This implementation is freely inspired by Boost.Random123
/// (https://github.com/DEShawResearch/Random123-Boost)
///
/// \tparam N number of words of the counter, 2 or 4. The key has N / 2 words
/// \tparam Uint unsigned integer type used for the words of the counter
/// \tparam R number of rounds of the cipher, 10 by default
/// \tparam Constants the multipliers and Weyl constants of the generator
template <unsigned N, typename Uint, unsigned R = 10, typename Constants = impl::philox_constants<N, Uint>>
class philox {
  static_assert(N == 2 || N == 4, "the number of words of the counter should be 2 or 4");

public:
  using domain_type = std::array<Uint, N>;
  using range_type = std::array<Uint, N>;
  using key_type = std::array<Uint, N / 2>;
  using uint_type = Uint;

  /// number of rounds performed by the generator
  static constexpr unsigned number_of_rounds = R;

  /// construct a generator with a key set to zero
  ALEA_HOST_DEVICE constexpr philox() : k() {}

  /// construct a generator with the key `new_key`
  ALEA_HOST_DEVICE explicit constexpr philox(key_type new_key) : k(new_key) {}

  constexpr philox(const philox&) = default;
  constexpr philox(philox&&) = default;

  philox& operator=(const philox&) = default;
  philox& operator=(philox&&) = default;

  /// set the key of the generator
  ALEA_HOST_DEVICE void set_key(key_type new_key) { k = new_key; }

  /// get the key of the generator
  ALEA_HOST_DEVICE key_type get_key() const { return k; }

  ALEA_HOST_DEVICE bool operator==(const philox& rhs) const { return k == rhs.k; }

  ALEA_HOST_DEVICE bool operator!=(const philox& rhs) const { return k != rhs.k; }

  /// encrypt the counter `counter` with the current key of the generator
  ///
  /// the operation is stateless: the same (key, counter) pair always produces
  /// the same block, whatever the number of times and the order of the calls.
  ALEA_HOST_DEVICE constexpr range_type operator()(const domain_type& counter) const {
    domain_type c(counter);
    key_type kcopy(k);

    impl::philox_rounds_functor<R, uint_type, Constants, N> func;
    func(c, kcopy);

    return c;
  }

private:
  key_type k;
};

using philox2x32 = philox<2, std::uint32_t>;
using philox4x32 = philox<4, std::uint32_t>;

using philox2x64 = philox<2, std::uint64_t>;
using philox4x64 = philox<4, std::uint64_t>;

/// philox4x64 benefits from the native 64x64 -> 128 bit multiply of the
/// current platforms and is the recommended default
using philox_default = philox4x64;

} // namespace alea
