/**
 * Copyright (c) 2026, Adrien Devresse <adev@adev.name>
 *
 * Boost Software License - Version 1.0
 *
 * Permission is hereby granted, free of charge, to any person or organization
 * obtaining a copy of the software and accompanying documentation covered by
 * this license (the "Software") to use, reproduce, display, distribute,
 * execute, and transmit the Software, and to prepare derivative works of the
 * Software, and to permit third-parties to whom the Software is furnished to
 * do so, all subject to the following:
 *
 * The copyright notices in the Software and this entire statement, including
 * the above license grant, this restriction and the following disclaimer,
 * must be included in all copies of the Software, in whole or in part, and
 * all derivative works of the Software, unless such copies or derivative
 * works are solely in the form of machine-executable object code generated by
 * a source language processor.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
 * SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE
 * FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
 * ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
 * DEALINGS IN THE SOFTWARE.
 *
 */
#pragma once

#include <concepts>
#include <cstddef>
#include <type_traits>

//
// The concepts describing the interface shared by the counter based random
// generators (CBRNG) of alea: philox, threefry and ars. counter_engine is
// written against this interface and can therefore adapt any conforming
// generator into a C++ random engine.
//

namespace alea {

/// `word_block` models the fixed size block of unsigned words used for the
/// counter, the key and the output of a CBRNG: it is indexable, iterable and
/// knows its size at compile time.
///
/// \tparam T the block type, for example `std::array<std::uint64_t, 4>`
template <typename T>
concept word_block = requires(T block, const T const_block, std::size_t index) {
  typename T::value_type;                                                // the words have a value type ...
  requires std::is_unsigned_v<typename T::value_type>;                   // ... which must be an unsigned integer
  { const_block.size() } -> std::convertible_to<std::size_t>;            // fixed size known at compile time
  { const_block[index] } -> std::convertible_to<typename T::value_type>; // random access to a word
  { block.begin() }; // iterable, so the counter can be incremented word by word
  { block.end() };
};

/// `cbrng` models a counter based random generator: a state-less block cipher
/// keyed by an identifier of the stream, encrypting a counter block into a
/// range block.
///
/// A conforming generator exposes:
///   - `uint_type`, the unsigned type of the words;
///   - `domain_type` and `range_type`, the input counter and output block;
///   - `key_type`, the type of the key selecting the stream;
///   - `number_of_rounds`, the number of cipher rounds performed;
///   - `set_key()`/`get_key()`, to read and write the key (the only state);
///   - `operator()(const domain_type&) const`, the state-less encryption.
///
/// Philox, threefry and ars all satisfy this concept.
///
/// \tparam T the generator type, for example `alea::threefry4x64`
template <typename T>
concept cbrng =
    // a value type that can be copied, defaulted and compared by key
    std::semiregular<T> && std::equality_comparable<T> &&
    // the nested types defining a stream: word, counter, output and key
    requires {
      typename T::uint_type;
      typename T::domain_type;
      typename T::range_type;
      typename T::key_type;
    } &&
    // counter, key and output are blocks of unsigned words of a single type
    std::is_unsigned_v<typename T::uint_type> && word_block<typename T::domain_type> &&
    word_block<typename T::range_type> && word_block<typename T::key_type> &&
    std::same_as<typename T::domain_type::value_type, typename T::uint_type> &&
    std::same_as<typename T::range_type::value_type, typename T::uint_type> &&
    std::same_as<typename T::key_type::value_type, typename T::uint_type> &&
    // an output block can be assigned back to a counter block
    std::convertible_to<typename T::range_type, typename T::domain_type> &&
    // expose the number of rounds, read/write the key (the only state) and
    // encrypt a counter without mutating the generator
    requires(T generator, const T const_generator, const typename T::domain_type& counter, typename T::key_type key) {
      { T::number_of_rounds } -> std::convertible_to<unsigned>;
      { const_generator.get_key() } -> std::same_as<typename T::key_type>;
      { generator.set_key(key) } -> std::same_as<void>;
      { const_generator(counter) } -> std::same_as<typename T::range_type>;
    };

} // namespace alea
