/**
 * Copyright (c) 2026, Adrien Devresse <adev@adev.name>
 *
 * Boost Software License - Version 1.0
 *
 * Permission is hereby granted, free of charge, to any person or organization
 * obtaining a copy of the software and accompanying documentation covered by
 * this license (the "Software") to use, reproduce, display, distribute,
 * execute, and transmit the Software, and to prepare derivative works of the
 * Software, and to permit third-parties to whom the Software is furnished to
 * do so, all subject to the following:
 *
 * The copyright notices in the Software and this entire statement, including
 * the above license grant, this restriction and the following disclaimer,
 * must be included in all copies of the Software, in whole or in part, and
 * all derivative works of the Software, unless such copies or derivative
 * works are solely in the form of machine-executable object code generated by
 * a source language processor.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
 * SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE
 * FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
 * ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
 * DEALINGS IN THE SOFTWARE.
 *
 */
#pragma once

#include <array>
#include <cstddef>
#include <cstdint>
#include <span>

//
// SHA-256 as specified in FIPS 180-4 and RFC 6234.
//
// The tests validate this implementation bit to bit against a reference
// implementation (https://github.com/B-Con/crypto-algorithms, sha256.c)
// fetched with FetchContent when -DALEA_ENABLE_VALIDATION_SHA256=ON.
//
// Like blake2b and blake2s, the hasher is a plain value struct with an
// inline state, no dynamic allocation and no virtual member, and it is usable
// during constant evaluation.
//

namespace alea {
namespace impl {

/// initial hash value of SHA-256
inline constexpr std::array<std::uint32_t, 8> sha256_iv = {
    0x6a09e667u, 0xbb67ae85u, 0x3c6ef372u, 0xa54ff53au, 0x510e527fu, 0x9b05688cu, 0x1f83d9abu, 0x5be0cd19u,
};

/// round constants of SHA-256 (first 32 bits of the fractional parts of the
/// cube roots of the first 64 primes)
inline constexpr std::array<std::uint32_t, 64> sha256_k = {
    0x428a2f98u, 0x71374491u, 0xb5c0fbcfu, 0xe9b5dba5u, 0x3956c25bu, 0x59f111f1u, 0x923f82a4u, 0xab1c5ed5u,
    0xd807aa98u, 0x12835b01u, 0x243185beu, 0x550c7dc3u, 0x72be5d74u, 0x80deb1feu, 0x9bdc06a7u, 0xc19bf174u,
    0xe49b69c1u, 0xefbe4786u, 0x0fc19dc6u, 0x240ca1ccu, 0x2de92c6fu, 0x4a7484aau, 0x5cb0a9dcu, 0x76f988dau,
    0x983e5152u, 0xa831c66du, 0xb00327c8u, 0xbf597fc7u, 0xc6e00bf3u, 0xd5a79147u, 0x06ca6351u, 0x14292967u,
    0x27b70a85u, 0x2e1b2138u, 0x4d2c6dfcu, 0x53380d13u, 0x650a7354u, 0x766a0abbu, 0x81c2c92eu, 0x92722c85u,
    0xa2bfe8a1u, 0xa81a664bu, 0xc24b8b70u, 0xc76c51a3u, 0xd192e819u, 0xd6990624u, 0xf40e3585u, 0x106aa070u,
    0x19a4c116u, 0x1e376c08u, 0x2748774cu, 0x34b0bcb5u, 0x391c0cb3u, 0x4ed8aa4au, 0x5b9cca4fu, 0x682e6ff3u,
    0x748f82eeu, 0x78a5636fu, 0x84c87814u, 0x8cc70208u, 0x90befffau, 0xa4506cebu, 0xbef9a3f7u, 0xc67178f2u,
};

/// load an unsigned integer stored in big endian order
template <typename uint_type> constexpr uint_type load_be(const std::byte* bytes) noexcept {
  uint_type value = 0;
  for (std::size_t i = 0; i < sizeof(uint_type); ++i) {
    value = static_cast<uint_type>((value << 8) | static_cast<uint_type>(std::to_integer<unsigned int>(bytes[i])));
  }
  return value;
}

/// store an unsigned integer in big endian order
template <typename uint_type> constexpr void store_be(std::byte* bytes, uint_type value) noexcept {
  for (std::size_t i = 0; i < sizeof(uint_type); ++i) {
    bytes[i] = static_cast<std::byte>((value >> (8u * (sizeof(uint_type) - 1 - i))) & static_cast<uint_type>(0xff));
  }
}

/// circular right rotation
constexpr std::uint32_t sha256_rotr(std::uint32_t value, unsigned int bits) noexcept {
  return (value >> bits) | (value << (32u - bits));
}

/// logical functions of the SHA-2 family
constexpr std::uint32_t sha256_choose(std::uint32_t x, std::uint32_t y, std::uint32_t z) noexcept {
  return (x & y) ^ (~x & z);
}

constexpr std::uint32_t sha256_majority(std::uint32_t x, std::uint32_t y, std::uint32_t z) noexcept {
  return (x & y) ^ (x & z) ^ (y & z);
}

constexpr std::uint32_t sha256_big_sigma0(std::uint32_t x) noexcept {
  return sha256_rotr(x, 2u) ^ sha256_rotr(x, 13u) ^ sha256_rotr(x, 22u);
}

constexpr std::uint32_t sha256_big_sigma1(std::uint32_t x) noexcept {
  return sha256_rotr(x, 6u) ^ sha256_rotr(x, 11u) ^ sha256_rotr(x, 25u);
}

constexpr std::uint32_t sha256_small_sigma0(std::uint32_t x) noexcept {
  return sha256_rotr(x, 7u) ^ sha256_rotr(x, 18u) ^ (x >> 3u);
}

constexpr std::uint32_t sha256_small_sigma1(std::uint32_t x) noexcept {
  return sha256_rotr(x, 17u) ^ sha256_rotr(x, 19u) ^ (x >> 10u);
}

/// the SHA-256 compression function over a single 64 byte block
constexpr void sha256_compress(std::array<std::uint32_t, 8>& h, const std::byte* block) noexcept {
  std::array<std::uint32_t, 64> w{};
  for (std::size_t i = 0; i < 16; ++i) {
    w[i] = load_be<std::uint32_t>(block + i * 4);
  }
  for (std::size_t i = 16; i < 64; ++i) {
    w[i] = sha256_small_sigma1(w[i - 2]) + w[i - 7] + sha256_small_sigma0(w[i - 15]) + w[i - 16];
  }

  std::uint32_t a = h[0];
  std::uint32_t b = h[1];
  std::uint32_t c = h[2];
  std::uint32_t d = h[3];
  std::uint32_t e = h[4];
  std::uint32_t f = h[5];
  std::uint32_t g = h[6];
  std::uint32_t hh = h[7];

  for (std::size_t i = 0; i < 64; ++i) {
    const std::uint32_t t1 = hh + sha256_big_sigma1(e) + sha256_choose(e, f, g) + sha256_k[i] + w[i];
    const std::uint32_t t2 = sha256_big_sigma0(a) + sha256_majority(a, b, c);
    hh = g;
    g = f;
    f = e;
    e = d + t1;
    d = c;
    c = b;
    b = a;
    a = t1 + t2;
  }

  h[0] += a;
  h[1] += b;
  h[2] += c;
  h[3] += d;
  h[4] += e;
  h[5] += f;
  h[6] += g;
  h[7] += hh;
}

} // namespace impl

/// SHA-256 with a 32 byte digest
struct sha256 {
  /// size in bytes of the digest returned by finalize()
  static constexpr std::size_t digest_size = 32;
  /// size in bytes of the blocks processed by the compression function
  static constexpr std::size_t block_size = 64;
  /// type returned by finalize()
  using digest_type = std::array<std::byte, digest_size>;

  /// chaining value
  std::array<std::uint32_t, 8> h = impl::sha256_iv;
  /// bytes not yet compressed, always fewer than block_size
  std::array<std::byte, block_size> buffer = {};
  /// number of valid bytes in buffer
  std::size_t buffer_used = 0;
  /// number of message bytes already fed to the compression function
  std::uint64_t counter = 0;

  /// bring the hasher back to its initial state, all the members are reset
  constexpr void reset() noexcept {
    h = impl::sha256_iv;
    buffer_used = 0;
    counter = 0;
  }

  /// absorb a chunk of the message
  constexpr void update(std::span<const std::byte> data) noexcept {
    const std::byte* input = data.data();
    std::size_t remaining = data.size();

    // complete a partially filled block first, if any
    if (buffer_used != 0) {
      const std::size_t space = block_size - buffer_used;
      const std::size_t to_copy = (space < remaining) ? space : remaining;
      for (std::size_t i = 0; i < to_copy; ++i) {
        buffer[buffer_used + i] = input[i];
      }
      buffer_used += to_copy;
      input += to_copy;
      remaining -= to_copy;

      if (buffer_used < block_size) {
        // the block is still incomplete, everything has been buffered
        return;
      }

      counter += block_size;
      impl::sha256_compress(h, buffer.data());
      buffer_used = 0;
    }

    // compress the full blocks directly out of the input
    while (remaining >= block_size) {
      counter += block_size;
      impl::sha256_compress(h, input);
      input += block_size;
      remaining -= block_size;
    }

    // keep the tail for the next call
    for (std::size_t i = 0; i < remaining; ++i) {
      buffer[i] = input[i];
    }
    buffer_used = remaining;
  }

  /// return the SHA-256 digest of everything absorbed so far, the hasher is
  /// left in a usable but unspecified state
  constexpr digest_type finalize() noexcept {
    const std::uint64_t bit_length = (counter + buffer_used) * 8;

    std::array<std::byte, 2 * block_size> padded = {};
    for (std::size_t i = 0; i < buffer_used; ++i) {
      padded[i] = buffer[i];
    }
    padded[buffer_used] = static_cast<std::byte>(0x80);

    // a 64 bit length is appended in the last eight bytes, which requires an
    // extra block when the message tail leaves less than nine free bytes
    const std::size_t padded_size = (buffer_used < block_size - 8) ? block_size : 2 * block_size;
    impl::store_be(padded.data() + padded_size - 8, bit_length);

    for (std::size_t offset = 0; offset < padded_size; offset += block_size) {
      impl::sha256_compress(h, padded.data() + offset);
    }

    digest_type digest{};
    for (std::size_t i = 0; i < 8; ++i) {
      impl::store_be(digest.data() + i * 4, h[i]);
    }
    return digest;
  }
};

} // namespace alea
