/**
 * Copyright (c) 2026, Adrien Devresse <adev@adev.name>
 *
 * Boost Software License - Version 1.0
 *
 * Permission is hereby granted, free of charge, to any person or organization
 * obtaining a copy of the software and accompanying documentation covered by
 * this license (the "Software") to use, reproduce, display, distribute,
 * execute, and transmit the Software, and to prepare derivative works of the
 * Software, and to permit third-parties to whom the Software is furnished to
 * do so, all subject to the following:
 *
 * The copyright notices in the Software and this entire statement, including
 * the above license grant, this restriction and the following disclaimer,
 * must be included in all copies of the Software, in whole or in part, and
 * all derivative works of the Software, unless such copies or derivative
 * works are solely in the form of machine-executable object code generated by
 * a source language processor.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
 * SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE
 * FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
 * ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
 * DEALINGS IN THE SOFTWARE.
 *
 */
#pragma once

#include <array>
#include <cstddef>
#include <cstdint>

#include "alea/gpu_portability.hpp"
#include "alea/impl/threefry_impl.hpp"

//
// This work is derivated from the Boost.Random123 repository available here
// https://github.com/DEShawResearch/Random123-Boost
//

namespace alea {

/// threefry is a state-less counter based random generator, derivated from the
/// block cipher threefish, part of "The Skein Hash Function Family" by
///   Niels Ferguson, Stefan Lucks, Bruce Schneier, Doug Whiting,
///   Mihir Bellare, Tadayoshi Kohno, Jon Callas, Jesse Walker
///
/// threefry has been presented at SC11 in the publication
///   "Parallel random numbers: as easy as 1, 2, 3".
///    John K. Salmon, Mark A. Moraes, Ron O. Dror, David E. Shaw
///    (doi:10.1145/2063384.2063405)
///
/// This implementation is freely inspired by Boost.Random123
/// (https://github.com/DEShawResearch/Random123-Boost)
///
/// \tparam N number of words of the counter and of the key, 2 or 4
/// \tparam Uint unsigned integer type used for the words of the counter
/// \tparam R number of rounds of the cipher, 20 by default
/// \tparam Constants the parity and rotation constants of the generator
template <unsigned N, typename Uint, unsigned R = 20, typename Constants = impl::threefry_constants<N, Uint>>
class threefry {
  static_assert(N == 2 || N == 4, "the number of words of the counter should be 2 or 4");

public:
  using domain_type = std::array<Uint, N>;
  using range_type = std::array<Uint, N>;
  using key_type = std::array<Uint, N>;
  using uint_type = Uint;

  /// number of rounds performed by the generator
  static constexpr unsigned number_of_rounds = R;

  /// construct a generator with a key set to zero
  ALEA_HOST_DEVICE constexpr threefry() : k() {}

  /// construct a generator with the key `new_key`
  ALEA_HOST_DEVICE explicit constexpr threefry(key_type new_key) : k(new_key) {}

  constexpr threefry(const threefry&) = default;
  constexpr threefry(threefry&&) = default;

  threefry& operator=(const threefry&) = default;
  threefry& operator=(threefry&&) = default;

  /// set the key of the generator
  ALEA_HOST_DEVICE void set_key(key_type new_key) { k = new_key; }

  /// get the key of the generator
  ALEA_HOST_DEVICE key_type get_key() const { return k; }

  ALEA_HOST_DEVICE bool operator==(const threefry& rhs) const { return k == rhs.k; }

  ALEA_HOST_DEVICE bool operator!=(const threefry& rhs) const { return k != rhs.k; }

  /// encrypt the counter `counter` with the current key of the generator
  ///
  /// the operation is stateless: the same (key, counter) pair always produces
  /// the same block, whatever the number of times and the order of the calls.
  ALEA_HOST_DEVICE constexpr range_type operator()(const domain_type& counter) const {
    std::array<uint_type, N + 1> ks{};
    domain_type c(counter);

    // the schedule key ks is the key k extended with its parity
    // (xor of all its words) mixed with the threefry KS parity constant
    ks[N] = Constants::ks_parity();
    for (std::size_t i = 0; i < N; ++i) {
      ks[i] = k[i];
      ks[N] ^= k[i];
      c[i] += k[i];
    }

    impl::rounds_functor<R, R, uint_type, domain_type, Constants, N> func;
    func(ks, c);

    return c;
  }

private:
  key_type k;
};

using threefry2x32 = threefry<2, std::uint32_t>;
using threefry4x32 = threefry<4, std::uint32_t>;

using threefry2x64 = threefry<2, std::uint64_t>;
using threefry4x64 = threefry<4, std::uint64_t>;

/// threefry4x64 is crush-resistant and the fastest one on most of the current
/// platforms: it is the recommended default
using threefry_default = threefry4x64;

} // namespace alea
