/**
 * Copyright (c) 2026, Adrien Devresse <adev@adev.name>
 *
 * Boost Software License - Version 1.0
 *
 * Permission is hereby granted, free of charge, to any person or organization
 * obtaining a copy of the software and accompanying documentation covered by
 * this license (the "Software") to use, reproduce, display, distribute,
 * execute, and transmit the Software, and to prepare derivative works of the
 * Software, and to permit third-parties to whom the Software is furnished to
 * do so, all subject to the following:
 *
 * The copyright notices in the Software and this entire statement, including
 * the above license grant, this restriction and the following disclaimer,
 * must be included in all copies of the Software, in whole or in part, and
 * all derivative works of the Software, unless such copies or derivative
 * works are solely in the form of machine-executable object code generated by
 * a source language processor.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
 * SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE
 * FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
 * ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
 * DEALINGS IN THE SOFTWARE.
 *
 */
#pragma once

#include <array>
#include <cstddef>
#include <cstdint>
#include <type_traits>

#include "alea/gpu_portability.hpp"

//
// Internal details of the ARS (Advanced Randomization System) counter based
// random generator.
// This header is not meant to be included directly, include <alea/ars.hpp>
// or <alea/random.hpp> instead.
//
// ARS applies the AES round function to a 128 bit counter, using a simplified
// Weyl key schedule instead of the cryptographic AES key expansion:
//
//   round key_0 = user key
//   round key_i = round key_(i - 1) + Weyl constant
//
// The AES round function is available as a dedicated instruction on most
// modern CPUs (AES-NI on x86, the ARMv8 Cryptography Extensions on AArch64).
// The optimized paths below are selected at compile time from the predefined
// compiler macros; on every other platform, and during constant evaluation,
// the portable software implementation is used instead. The two
// implementations produce bit-to-bit identical results.
//

// detect the AES instruction set of the platform
//
// ALEA_ARS_DISABLE_HW forces the portable software implementation. It is used
// by the validation tests to exercise the fallback even on a platform that
// provides the instructions, the same way ALEA_PHILOX_DISABLE_INT128 does for
// philox. The hardware paths are never used during the CUDA device pass: the
// AES instructions are a host feature and only the software path is defined
// there.
#if !defined(ALEA_ARS_DISABLE_HW) && !defined(__CUDA_ARCH__)

// x86 / x86_64 AES-NI: the compiler defines __AES__ when it is allowed to
// emit the AES instructions, for example when built with -maes
#if defined(__AES__) && (defined(__x86_64__) || defined(__i386__) || defined(_M_X64) || defined(_M_IX86))
#define ALEA_ARS_USE_AESNI 1

// AArch64 Cryptography Extensions: the compiler defines __ARM_FEATURE_AES
// when it is allowed to emit the AES instructions, for example when built with
// -march=armv8-a+crypto
#elif defined(__ARM_FEATURE_AES)
#define ALEA_ARS_USE_ARM_CRYPTO 1
#endif

#endif // hardware detection

#if defined(ALEA_ARS_USE_AESNI)
#include <emmintrin.h>
#include <wmmintrin.h>
#endif

#if defined(ALEA_ARS_USE_ARM_CRYPTO)
#include <arm_neon.h>
#endif

namespace alea {
namespace impl {

/// the AES state is an array of 16 bytes laid out column by column: the byte
/// at index `row + 4 * col` is the element (row, col) of the AES state matrix
using aes_state = std::array<std::uint8_t, 16>;

/// the AES substitution box
///
/// the table is a function local constant: it is evaluated at compile time
/// when the software implementation runs inside a constant expression, and
/// materialized as a read-only table otherwise. It is also the reason why the
/// software fallback stays constexpr friendly.
ALEA_HOST_DEVICE constexpr std::uint8_t aes_sub_byte(std::uint8_t value) {
  constexpr std::uint8_t table[256] = {
      0x63, 0x7c, 0x77, 0x7b, 0xf2, 0x6b, 0x6f, 0xc5, 0x30, 0x01, 0x67, 0x2b, 0xfe, 0xd7, 0xab, 0x76, 0xca, 0x82, 0xc9,
      0x7d, 0xfa, 0x59, 0x47, 0xf0, 0xad, 0xd4, 0xa2, 0xaf, 0x9c, 0xa4, 0x72, 0xc0, 0xb7, 0xfd, 0x93, 0x26, 0x36, 0x3f,
      0xf7, 0xcc, 0x34, 0xa5, 0xe5, 0xf1, 0x71, 0xd8, 0x31, 0x15, 0x04, 0xc7, 0x23, 0xc3, 0x18, 0x96, 0x05, 0x9a, 0x07,
      0x12, 0x80, 0xe2, 0xeb, 0x27, 0xb2, 0x75, 0x09, 0x83, 0x2c, 0x1a, 0x1b, 0x6e, 0x5a, 0xa0, 0x52, 0x3b, 0xd6, 0xb3,
      0x29, 0xe3, 0x2f, 0x84, 0x53, 0xd1, 0x00, 0xed, 0x20, 0xfc, 0xb1, 0x5b, 0x6a, 0xcb, 0xbe, 0x39, 0x4a, 0x4c, 0x58,
      0xcf, 0xd0, 0xef, 0xaa, 0xfb, 0x43, 0x4d, 0x33, 0x85, 0x45, 0xf9, 0x02, 0x7f, 0x50, 0x3c, 0x9f, 0xa8, 0x51, 0xa3,
      0x40, 0x8f, 0x92, 0x9d, 0x38, 0xf5, 0xbc, 0xb6, 0xda, 0x21, 0x10, 0xff, 0xf3, 0xd2, 0xcd, 0x0c, 0x13, 0xec, 0x5f,
      0x97, 0x44, 0x17, 0xc4, 0xa7, 0x7e, 0x3d, 0x64, 0x5d, 0x19, 0x73, 0x60, 0x81, 0x4f, 0xdc, 0x22, 0x2a, 0x90, 0x88,
      0x46, 0xee, 0xb8, 0x14, 0xde, 0x5e, 0x0b, 0xdb, 0xe0, 0x32, 0x3a, 0x0a, 0x49, 0x06, 0x24, 0x5c, 0xc2, 0xd3, 0xac,
      0x62, 0x91, 0x95, 0xe4, 0x79, 0xe7, 0xc8, 0x37, 0x6d, 0x8d, 0xd5, 0x4e, 0xa9, 0x6c, 0x56, 0xf4, 0xea, 0x65, 0x7a,
      0xae, 0x08, 0xba, 0x78, 0x25, 0x2e, 0x1c, 0xa6, 0xb4, 0xc6, 0xe8, 0xdd, 0x74, 0x1f, 0x4b, 0xbd, 0x8b, 0x8a, 0x70,
      0x3e, 0xb5, 0x66, 0x48, 0x03, 0xf6, 0x0e, 0x61, 0x35, 0x57, 0xb9, 0x86, 0xc1, 0x1d, 0x9e, 0xe1, 0xf8, 0x98, 0x11,
      0x69, 0xd9, 0x8e, 0x94, 0x9b, 0x1e, 0x87, 0xe9, 0xce, 0x55, 0x28, 0xdf, 0x8c, 0xa1, 0x89, 0x0d, 0xbf, 0xe6, 0x42,
      0x68, 0x41, 0x99, 0x2d, 0x0f, 0xb0, 0x54, 0xbb, 0x16};
  return table[value];
}

/// multiply by x in the finite field GF(2^8), i.e. by 2 in the AES
/// MixColumns matrix
ALEA_HOST_DEVICE constexpr std::uint8_t aes_xtime(std::uint8_t value) {
  constexpr std::uint8_t reduction_polynomial = 0x1b;
  return static_cast<std::uint8_t>((value << 1) ^ ((value & 0x80U) != 0U ? reduction_polynomial : 0x00U));
}

/// convert the four little endian words of a counter or of a key into the
/// byte oriented AES state
ALEA_HOST_DEVICE constexpr aes_state aes_to_state(const std::array<std::uint32_t, 4>& words) {
  aes_state state{};
  for (std::size_t word = 0; word < 4; ++word) {
    state[4 * word + 0] = static_cast<std::uint8_t>(words[word]);
    state[4 * word + 1] = static_cast<std::uint8_t>(words[word] >> 8);
    state[4 * word + 2] = static_cast<std::uint8_t>(words[word] >> 16);
    state[4 * word + 3] = static_cast<std::uint8_t>(words[word] >> 24);
  }
  return state;
}

/// inverse of aes_to_state
ALEA_HOST_DEVICE constexpr std::array<std::uint32_t, 4> aes_from_state(const aes_state& state) {
  std::array<std::uint32_t, 4> words{};
  for (std::size_t word = 0; word < 4; ++word) {
    words[word] = static_cast<std::uint32_t>(state[4 * word + 0]) |
                  (static_cast<std::uint32_t>(state[4 * word + 1]) << 8) |
                  (static_cast<std::uint32_t>(state[4 * word + 2]) << 16) |
                  (static_cast<std::uint32_t>(state[4 * word + 3]) << 24);
  }
  return words;
}

/// AES SubBytes: replace every byte of the state by its S-box image
ALEA_HOST_DEVICE constexpr void aes_sub_bytes(aes_state& state) {
  for (std::uint8_t& byte : state) {
    byte = aes_sub_byte(byte);
  }
}

/// AES ShiftRows: cyclically shift the row `row` of the state left by `row`
/// positions
ALEA_HOST_DEVICE constexpr void aes_shift_rows(aes_state& state) {
  const aes_state input(state);
  for (std::size_t col = 0; col < 4; ++col) {
    for (std::size_t row = 0; row < 4; ++row) {
      state[row + 4 * col] = input[row + 4 * ((col + row) % 4)];
    }
  }
}

/// AES MixColumns: multiply every column of the state by the fixed AES
/// polynomial matrix
ALEA_HOST_DEVICE constexpr void aes_mix_columns(aes_state& state) {
  const aes_state input(state);
  for (std::size_t col = 0; col < 4; ++col) {
    const std::uint8_t a0 = input[4 * col + 0];
    const std::uint8_t a1 = input[4 * col + 1];
    const std::uint8_t a2 = input[4 * col + 2];
    const std::uint8_t a3 = input[4 * col + 3];

    state[4 * col + 0] = static_cast<std::uint8_t>(aes_xtime(a0) ^ (aes_xtime(a1) ^ a1) ^ a2 ^ a3);
    state[4 * col + 1] = static_cast<std::uint8_t>(a0 ^ aes_xtime(a1) ^ (aes_xtime(a2) ^ a2) ^ a3);
    state[4 * col + 2] = static_cast<std::uint8_t>(a0 ^ a1 ^ aes_xtime(a2) ^ (aes_xtime(a3) ^ a3));
    state[4 * col + 3] = static_cast<std::uint8_t>((aes_xtime(a0) ^ a0) ^ a1 ^ a2 ^ aes_xtime(a3));
  }
}

/// AES AddRoundKey: xor the round key into the state
ALEA_HOST_DEVICE constexpr void aes_add_round_key(aes_state& state, const aes_state& round_key) {
  for (std::size_t i = 0; i < state.size(); ++i) {
    state[i] ^= round_key[i];
  }
}

/// advance the ARS round key along its Weyl sequence
///
/// the 128 bit key is seen as two independent 64 bit integers, each of them
/// incremented by its own Weyl constant. This mirrors the `_mm_add_epi64`
/// addition of the reference implementation and, on purpose, does not carry
/// from the low half into the high half.
ALEA_HOST_DEVICE constexpr void ars_advance_key(std::array<std::uint32_t, 4>& key) {
  constexpr std::uint64_t low_weyl = UINT64_C(0x9E3779B97F4A7C15);  // the golden ratio
  constexpr std::uint64_t high_weyl = UINT64_C(0xBB67AE8584CAA73B); // sqrt(3) - 1

  const std::uint64_t low =
      (static_cast<std::uint64_t>(key[0]) | (static_cast<std::uint64_t>(key[1]) << 32)) + low_weyl;
  const std::uint64_t high =
      (static_cast<std::uint64_t>(key[2]) | (static_cast<std::uint64_t>(key[3]) << 32)) + high_weyl;

  key[0] = static_cast<std::uint32_t>(low);
  key[1] = static_cast<std::uint32_t>(low >> 32);
  key[2] = static_cast<std::uint32_t>(high);
  key[3] = static_cast<std::uint32_t>(high >> 32);
}

/// one AES encryption round: SubBytes, ShiftRows, MixColumns, AddRoundKey
ALEA_HOST_DEVICE constexpr void aes_round(aes_state& state, const aes_state& round_key) {
  aes_sub_bytes(state);
  aes_shift_rows(state);
  aes_mix_columns(state);
  aes_add_round_key(state, round_key);
}

/// the AES last round: SubBytes, ShiftRows, AddRoundKey, no MixColumns
ALEA_HOST_DEVICE constexpr void aes_last_round(aes_state& state, const aes_state& round_key) {
  aes_sub_bytes(state);
  aes_shift_rows(state);
  aes_add_round_key(state, round_key);
}

/// portable software ARS encryption
///
/// it is the reference of the family: the hardware implementations below
/// must return exactly the same block, and this is the implementation used
/// during constant evaluation and on the CUDA device.
template <unsigned R>
ALEA_HOST_DEVICE constexpr std::array<std::uint32_t, 4> ars_encrypt_software(std::array<std::uint32_t, 4> counter,
                                                                             std::array<std::uint32_t, 4> key) {
  aes_state state = aes_to_state(counter);
  aes_add_round_key(state, aes_to_state(key));

  for (unsigned round = 1; round < R; ++round) {
    ars_advance_key(key);
    aes_round(state, aes_to_state(key));
  }

  // the last round uses an AddRoundKey without MixColumns, and its round key
  // is the next one of the Weyl sequence
  ars_advance_key(key);
  aes_last_round(state, aes_to_state(key));

  return aes_from_state(state);
}

#if defined(ALEA_ARS_USE_AESNI)

/// x86 / x86_64 ARS encryption with the AES-NI instructions
///
/// state and round key are held in the same 128 bit register layout as the
/// reference implementation: the four little endian counter words map to the
/// bytes 0 to 15 of the register. This function is host only: the macro is
/// not defined during the CUDA device pass.
template <unsigned R>
ALEA_HOST_DEVICE inline std::array<std::uint32_t, 4> ars_encrypt_hardware(std::array<std::uint32_t, 4> counter,
                                                                          std::array<std::uint32_t, 4> key) {
  __m128i state = _mm_loadu_si128(reinterpret_cast<const __m128i*>(counter.data()));
  const __m128i initial_key = _mm_loadu_si128(reinterpret_cast<const __m128i*>(key.data()));
  state = _mm_xor_si128(state, initial_key);

  for (unsigned round = 1; round < R; ++round) {
    ars_advance_key(key);
    const __m128i round_key = _mm_loadu_si128(reinterpret_cast<const __m128i*>(key.data()));
    state = _mm_aesenc_si128(state, round_key);
  }

  ars_advance_key(key);
  const __m128i last_round_key = _mm_loadu_si128(reinterpret_cast<const __m128i*>(key.data()));
  state = _mm_aesenclast_si128(state, last_round_key);

  std::array<std::uint32_t, 4> result{};
  _mm_storeu_si128(reinterpret_cast<__m128i*>(result.data()), state);
  return result;
}

#elif defined(ALEA_ARS_USE_ARM_CRYPTO)

/// AArch64 ARS encryption with the ARMv8 Cryptography Extensions
///
/// the ARM instructions do not have the exact semantics of the x86 ones:
/// `vaeseq_u8` performs AddRoundKey before SubBytes and ShiftRows, while the
/// x86 `aesenc` performs it after. A full ARM round is therefore
/// `AESMC(AESE(state, 0))` followed by an explicit xor with the round key, and
/// the last round is `AESE(state, 0)` followed by the same xor. This function
/// is host only: the macro is not defined during the CUDA device pass.
template <unsigned R>
ALEA_HOST_DEVICE inline std::array<std::uint32_t, 4> ars_encrypt_hardware(std::array<std::uint32_t, 4> counter,
                                                                          std::array<std::uint32_t, 4> key) {
  const uint8x16_t zero = vdupq_n_u8(0);
  uint8x16_t state = vld1q_u8(reinterpret_cast<const std::uint8_t*>(counter.data()));
  const uint8x16_t initial_key = vld1q_u8(reinterpret_cast<const std::uint8_t*>(key.data()));
  state = veorq_u8(state, initial_key);

  for (unsigned round = 1; round < R; ++round) {
    ars_advance_key(key);
    const uint8x16_t round_key = vld1q_u8(reinterpret_cast<const std::uint8_t*>(key.data()));
    state = veorq_u8(vaesmcq_u8(vaeseq_u8(state, zero)), round_key);
  }

  ars_advance_key(key);
  const uint8x16_t last_round_key = vld1q_u8(reinterpret_cast<const std::uint8_t*>(key.data()));
  state = veorq_u8(vaeseq_u8(state, zero), last_round_key);

  std::array<std::uint32_t, 4> result{};
  vst1q_u8(reinterpret_cast<std::uint8_t*>(result.data()), state);
  return result;
}

#endif

/// ARS encryption dispatch
///
/// during constant evaluation the portable software implementation is used,
/// so that the generator stays usable in constant expressions on every
/// platform, whatever the instruction set the compiler was told to target. At
/// run time the AES instructions are used when they are available, and the
/// software implementation otherwise.
template <unsigned R>
ALEA_HOST_DEVICE constexpr std::array<std::uint32_t, 4> ars_encrypt(std::array<std::uint32_t, 4> counter,
                                                                    std::array<std::uint32_t, 4> key) {
  if (std::is_constant_evaluated()) {
    return ars_encrypt_software<R>(counter, key);
  }

#if defined(ALEA_ARS_USE_AESNI) || defined(ALEA_ARS_USE_ARM_CRYPTO)
  return ars_encrypt_hardware<R>(counter, key);
#else
  return ars_encrypt_software<R>(counter, key);
#endif
}

} // namespace impl
} // namespace alea
