/**
 * Copyright (c) 2026, Adrien Devresse <adev@adev.name>
 *
 * Boost Software License - Version 1.0
 *
 * Permission is hereby granted, free of charge, to any person or organization
 * obtaining a copy of the software and accompanying documentation covered by
 * this license (the "Software") to use, reproduce, display, distribute,
 * execute, and transmit the Software, and to prepare derivative works of the
 * Software, and to permit third-parties to whom the Software is furnished to
 * do so, all subject to the following:
 *
 * The copyright notices in the Software and this entire statement, including
 * the above license grant, this restriction and the following disclaimer,
 * must be included in all copies of the Software, in whole or in part, and
 * all derivative works of the Software, unless such copies or derivative
 * works are solely in the form of machine-executable object code generated by
 * a source language processor.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
 * SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE
 * FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
 * ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
 * DEALINGS IN THE SOFTWARE.
 *
 */
#pragma once

#include <array>
#include <cstddef>
#include <cstdint>
#include <limits>
#include <type_traits>

//
// Internal details of the philox counter based random generator.
// This header is not meant to be included directly, include <alea/philox.hpp>
// or <alea/random.hpp> instead.
//

namespace alea {
namespace impl {

// the product of two words of `Uint` does not fit in `Uint`: the result of a
// philox round needs both the low and the high half of the product. The wide
// type below is the unsigned integer type able to hold that product.
template <typename Uint> struct wide_uint;

template <> struct wide_uint<std::uint32_t> {
  using type = std::uint64_t;
};

// the fast 64 bit multiply of philox relies on a double width integer type.
// When the platform does not provide one, or when ALEA_PHILOX_DISABLE_INT128 is
// defined, the portable fallback below is used instead: the validation tests
// compile an additional translation unit with this flag to exercise it.
#if defined(__SIZEOF_INT128__) && !defined(ALEA_PHILOX_DISABLE_INT128)
template <> struct wide_uint<std::uint64_t> {
  __extension__ using type = unsigned __int128;
};
#endif

#if defined(__SIZEOF_INT128__) && !defined(ALEA_PHILOX_DISABLE_INT128)

// return the low half of a * b and store the high half in `hi`
//
// the compiler recognizes the double width multiplication and reduces it to a
// single `mul` (32 bits) or `mulq` (64 bits) instruction on the supported
// architectures, which is the whole point of the philox round
template <typename Uint> constexpr Uint mulhilo(Uint a, Uint b, Uint& hi) {
  using wide_type = typename wide_uint<Uint>::type;
  constexpr unsigned word_bits = std::numeric_limits<Uint>::digits;

  const wide_type product = static_cast<wide_type>(a) * static_cast<wide_type>(b);
  hi = static_cast<Uint>(product >> word_bits);
  return static_cast<Uint>(product);
}

#else

// portable fallback for the platforms that do not provide a double width
// integer type: the product is reconstructed from four half word products
template <typename Uint> constexpr Uint mulhilo(Uint a, Uint b, Uint& hi) {
  constexpr unsigned half_bits = std::numeric_limits<Uint>::digits / 2;
  constexpr Uint low_mask = (static_cast<Uint>(1) << half_bits) - 1;

  const Uint a_low = a & low_mask;
  const Uint a_high = a >> half_bits;
  const Uint b_low = b & low_mask;
  const Uint b_high = b >> half_bits;

  const Uint low = a * b;
  const Uint a_high_b_low = a_high * b_low;
  const Uint a_low_b_high = a_low * b_high;
  const Uint cross = (a_high_b_low & low_mask) + (a_low_b_high & low_mask);

  hi = a_high * b_high + (a_high_b_low >> half_bits) + (a_low_b_high >> half_bits) + (cross >> half_bits) +
       ((low >> half_bits) < (cross & low_mask));
  return low;
}

#endif

// philox_constants holds the multipliers and the Weyl sequence constants of
// the philox generators. These constants are carefully chosen to achieve good
// randomization.
//  philox_constants<2, uint32_t>
//  philox_constants<2, uint64_t>
//  philox_constants<4, uint32_t>
//  philox_constants<4, uint64_t>
//
// See Salmon et al, "Parallel random numbers: as easy as 1, 2, 3" for
// information about how the constants were obtained.
template <unsigned N, typename Uint> struct philox_constants {};

// 2x32 constants
template <> struct philox_constants<2, std::uint32_t> {
  static constexpr std::uint32_t multipliers([[maybe_unused]] std::size_t pos) { return UINT32_C(0xD256D193); }

  static constexpr std::uint32_t weyl([[maybe_unused]] std::size_t pos) { return UINT32_C(0x9E3779B9); }
};

// 4x32 constants
template <> struct philox_constants<4, std::uint32_t> {
  static constexpr std::uint32_t multipliers(std::size_t pos) {
    return pos == 0 ? UINT32_C(0xD2511F53) : UINT32_C(0xCD9E8D57);
  }

  static constexpr std::uint32_t weyl(std::size_t pos) {
    return pos == 0 ? UINT32_C(0x9E3779B9) : UINT32_C(0xBB67AE85);
  }
};

// 2x64 constants
template <> struct philox_constants<2, std::uint64_t> {
  static constexpr std::uint64_t multipliers([[maybe_unused]] std::size_t pos) { return UINT64_C(0xD2B74407B1CE6E93); }

  static constexpr std::uint64_t weyl([[maybe_unused]] std::size_t pos) { return UINT64_C(0x9E3779B97F4A7C15); }
};

// 4x64 constants
template <> struct philox_constants<4, std::uint64_t> {
  static constexpr std::uint64_t multipliers(std::size_t pos) {
    return pos == 0 ? UINT64_C(0xD2E7470EE14C6C93) : UINT64_C(0xCA5A826395121157);
  }

  static constexpr std::uint64_t weyl(std::size_t pos) {
    return pos == 0 ? UINT64_C(0x9E3779B97F4A7C15) : UINT64_C(0xBB67AE8584CAA73B);
  }
};

// A philox round works on N words split in N/2 pairs. For every output pair i
// the round multiplies the pair (i + 1) modulo N/2 of the counter by the
// matching multiplier, xors the high half into the neighbouring word and uses
// the low half as the second word of the pair:
//
//   src = (i + 1) mod (N / 2)
//   (lo, hi) = mulhilo(M_src, c[2 src])
//   out[2 i]     = hi ^ c[2 i + 1] ^ key[i]
//   out[2 i + 1] = lo
//
// The key is then advanced along its Weyl sequence, one constant per pair.
// The same code covers the N == 2 and N == 4 variants: for N == 2 the pair
// permutation is the identity and the round degenerates to the usual 2xW one.
template <typename Uint, typename Constants, std::size_t N>
constexpr void philox_round(std::array<Uint, N>& c, std::array<Uint, N / 2>& key) {
  constexpr std::size_t half = N / 2;

  std::array<Uint, N> out{};
  for (std::size_t i = 0; i < half; ++i) {
    const std::size_t src = (i + 1) % half;

    Uint hi = 0;
    const Uint lo = mulhilo(Constants::multipliers(src), c[2 * src], hi);

    out[2 * i] = hi ^ c[2 * i + 1] ^ key[i];
    out[2 * i + 1] = lo;
  }

  c = out;
  for (std::size_t i = 0; i < half; ++i) {
    key[i] += Constants::weyl(i);
  }
}

// The number of rounds is known at compile time, so the recursion below is
// fully unrolled and the round loop disappears. This is the same technique
// used for threefry: it avoids the loop overhead and lets the compiler
// schedule the independent multiplications of every round.
template <std::size_t r_remain, typename Uint, typename Constants, std::size_t N> struct philox_rounds_functor {
  constexpr void operator()(std::array<Uint, N>& c, std::array<Uint, N / 2>& key) const {
    philox_round<Uint, Constants, N>(c, key);
    philox_rounds_functor<r_remain - 1, Uint, Constants, N>{}(c, key);
  }
};

template <typename Uint, typename Constants, std::size_t N> struct philox_rounds_functor<0, Uint, Constants, N> {
  constexpr void operator()(std::array<Uint, N>& c, std::array<Uint, N / 2>& key) const {
    (void)c;
    (void)key;
  }
};

} // namespace impl
} // namespace alea
