/**
 * Copyright (c) 2026, Adrien Devresse <adev@adev.name>
 *
 * Boost Software License - Version 1.0
 *
 * Permission is hereby granted, free of charge, to any person or organization
 * obtaining a copy of the software and accompanying documentation covered by
 * this license (the "Software") to use, reproduce, display, distribute,
 * execute, and transmit the Software, and to prepare derivative works of the
 * Software, and to permit third-parties to whom the Software is furnished to
 * do so, all subject to the following:
 *
 * The copyright notices in the Software and this entire statement, including
 * the above license grant, this restriction and the following disclaimer,
 * must be included in all copies of the Software, in whole or in part, and
 * all derivative works of the Software, unless such copies or derivative
 * works are solely in the form of machine-executable object code generated by
 * a source language processor.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
 * SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE
 * FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
 * ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
 * DEALINGS IN THE SOFTWARE.
 *
 */
#pragma once

#include <array>
#include <cstddef>
#include <cstdint>
#include <limits>

//
// Internal details of the threefry counter based random generator.
// This header is not meant to be included directly, include <alea/threefry.hpp>
// or <alea/random.hpp> instead.
//

namespace alea {
namespace impl {

// threefry_constants is an abstract template that is specialized with the
// KS_PARITY and rotation constants of the threefry generators.
// These constants are carefully chosen to achieve good randomization.
//  threefry_constants<2, uint32_t>
//  threefry_constants<2, uint64_t>
//  threefry_constants<4, uint32_t>
//  threefry_constants<4, uint64_t>
//
// See Salmon et al, or the original work on Threefish from Schneier et al for
// information about how the constants were obtained.
template <unsigned N, typename Uint> struct threefry_constants {};

// 2x32 constants
template <> struct threefry_constants<2, std::uint32_t> {
  static constexpr std::uint32_t ks_parity() { return UINT32_C(0x1BD11BDA); }

  static constexpr unsigned rotations(std::size_t pos) {
    constexpr unsigned rotation_table[8] = {13, 15, 26, 6, 17, 29, 16, 24};
    return rotation_table[pos];
  }
};

// 4x32 constants
template <> struct threefry_constants<4, std::uint32_t> {
  static constexpr std::uint32_t ks_parity() { return UINT32_C(0x1BD11BDA); }

  static constexpr unsigned rotations0(std::size_t pos) {
    constexpr unsigned rotation_table[8] = {10, 11, 13, 23, 6, 17, 25, 18};
    return rotation_table[pos];
  }

  static constexpr unsigned rotations1(std::size_t pos) {
    constexpr unsigned rotation_table[8] = {26, 21, 27, 5, 20, 11, 10, 20};
    return rotation_table[pos];
  }
};

// 2x64 constants
template <> struct threefry_constants<2, std::uint64_t> {
  static constexpr std::uint64_t ks_parity() { return UINT64_C(0x1BD11BDAA9FC1A22); }

  static constexpr unsigned rotations(std::size_t pos) {
    constexpr unsigned rotation_table[8] = {16, 42, 12, 31, 16, 32, 24, 21};
    return rotation_table[pos];
  }
};

// 4x64 constants
template <> struct threefry_constants<4, std::uint64_t> {
  static constexpr std::uint64_t ks_parity() { return UINT64_C(0x1BD11BDAA9FC1A22); }

  static constexpr unsigned rotations0(std::size_t pos) {
    constexpr unsigned rotation_table[8] = {14, 52, 23, 5, 25, 46, 58, 32};
    return rotation_table[pos];
  }

  static constexpr unsigned rotations1(std::size_t pos) {
    constexpr unsigned rotation_table[8] = {16, 57, 40, 37, 33, 12, 22, 32};
    return rotation_table[pos];
  }
};

template <typename Uint> constexpr Uint threefry_rotl(Uint x, unsigned s) {
  return (x << s) | (x >> (std::numeric_limits<Uint>::digits - s));
}

// The number of rounds is known at compile time.
// It allows us to use recursive partial template specialization and to avoid
// branching on conditions.
//
// good compilers (GCC, icc, clang) transform this into a single function
// without branching, we get a performance gain of x4 on Intel I7 compared to a
// loop version.
template <std::size_t r_remain, std::size_t r_max, typename Uint, typename Domain, typename Constants, std::size_t N>
struct rounds_functor {
  static_assert(N == 2 || N == 4, "the number of words of the counter should be 2 or 4");
};

template <std::size_t r_remain, std::size_t r_max, typename Uint, typename Domain, typename Constants>
struct rounds_functor<r_remain, r_max, Uint, Domain, Constants, 4> {
  using uint_type = Uint;
  using domain_type = Domain;

  constexpr void operator()(const std::array<uint_type, 5>& ks, domain_type& c) const {
    constexpr std::size_t r = r_max - r_remain;

    if ((r & 0x01)) {
      c[0] += c[3];
      c[2] += c[1];
      c[3] = threefry_rotl(c[3], Constants::rotations0(r % 8)) ^ c[0];
      c[1] = threefry_rotl(c[1], Constants::rotations1(r % 8)) ^ c[2];

      constexpr std::size_t r_next = r + 1;
      constexpr std::size_t r4 = r_next >> 2;
      constexpr std::size_t r_next_mod_4 = r_next % 4;

      if (r_next_mod_4 == 0) {
        c[0] += ks[(r4 + 0) % 5];
        c[1] += ks[(r4 + 1) % 5];
        c[2] += ks[(r4 + 2) % 5];
        c[3] += ks[(r4 + 3) % 5] + r4;
      }
    } else {
      c[0] += c[1];
      c[2] += c[3];
      c[1] = threefry_rotl(c[1], Constants::rotations0(r % 8)) ^ c[0];
      c[3] = threefry_rotl(c[3], Constants::rotations1(r % 8)) ^ c[2];
    }

    rounds_functor<r_remain - 1, r_max, uint_type, domain_type, Constants, 4> func;
    func(ks, c);
  }
};

template <std::size_t r_max, typename Uint, typename Domain, typename Constants>
struct rounds_functor<0, r_max, Uint, Domain, Constants, 4> {
  using uint_type = Uint;
  using domain_type = Domain;

  constexpr void operator()(const std::array<uint_type, 5>& ks, domain_type& c) const {
    (void)ks;
    (void)c;
  }
};

template <std::size_t r_remain, std::size_t r_max, typename Uint, typename Domain, typename Constants>
struct rounds_functor<r_remain, r_max, Uint, Domain, Constants, 2> {
  using uint_type = Uint;
  using domain_type = Domain;

  constexpr void operator()(const std::array<uint_type, 3>& ks, domain_type& c) const {
    constexpr std::size_t r = r_max - r_remain;

    c[0] += c[1];
    c[1] = threefry_rotl(c[1], Constants::rotations(r % 8));
    c[1] ^= c[0];

    constexpr std::size_t r_next = r + 1;
    constexpr std::size_t r4 = r_next >> 2;
    constexpr std::size_t r_next_mod_4 = r_next % 4;

    if (r_next_mod_4 == 0) {
      c[0] += ks[r4 % 3];
      c[1] += ks[(r4 + 1) % 3] + r4;
    }

    rounds_functor<r_remain - 1, r_max, uint_type, domain_type, Constants, 2> func;
    func(ks, c);
  }
};

template <std::size_t r_max, typename Uint, typename Domain, typename Constants>
struct rounds_functor<0, r_max, Uint, Domain, Constants, 2> {
  using uint_type = Uint;
  using domain_type = Domain;

  constexpr void operator()(const std::array<uint_type, 3>& ks, domain_type& c) const {
    (void)ks;
    (void)c;
  }
};

} // namespace impl
} // namespace alea
