/**
 * Copyright (c) 2026, Adrien Devresse <adev@adev.name>
 *
 * Boost Software License - Version 1.0
 *
 * Permission is hereby granted, free of charge, to any person or organization
 * obtaining a copy of the software and accompanying documentation covered by
 * this license (the "Software") to use, reproduce, display, distribute,
 * execute, and transmit the Software, and to prepare derivative works of the
 * Software, and to permit third-parties to whom the Software is furnished to
 * do so, all subject to the following:
 *
 * The copyright notices in the Software and this entire statement, including
 * the above license grant, this restriction and the following disclaimer,
 * must be included in all copies of the Software, in whole or in part, and
 * all derivative works of the Software, unless such copies or derivative
 * works are solely in the form of machine-executable object code generated by
 * a source language processor.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
 * SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE
 * FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
 * ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
 * DEALINGS IN THE SOFTWARE.
 *
 */

#define DOCTEST_CONFIG_IMPLEMENT_WITH_MAIN
#include "philox_validation_common.hpp"

//
// Validation of the portable fallback used by philox to multiply two 64 bit
// words when the platform does not provide a double width integer type, or
// when ALEA_PHILOX_DISABLE_INT128 is defined.
//
// This translation unit is only built when the platform supports the double
// width integer type: it is compiled with ALEA_PHILOX_DISABLE_INT128 so that
// the fallback replaces the fast multiply, and the two implementations can be
// checked against the same reference. The 32 bit generators are not repeated
// here: only the 64 bit multiply has a fallback, the 32 bit one always uses a
// 64 bit product.
//

namespace pv = alea::test::philox_validation;

TEST_CASE_TEMPLATE("philox fallback blocks are bit to bit identical to the reference random123", AleaCbrng,
                   alea::philox2x64, alea::philox4x64) {
  using ref_type = typename pv::reference_generator<AleaCbrng>::type;
  pv::run_random_block_validation<AleaCbrng, ref_type>();
}

TEST_CASE("philox fallback with non default round counts matches the reference random123") {
  pv::run_random_block_validation<alea::philox<4, std::uint64_t, 12>, r123::Philox4x64_R<12>>();
  pv::run_random_block_validation<alea::philox<2, std::uint64_t, 7>, r123::Philox2x64_R<7>>();
}

TEST_CASE_TEMPLATE("counter_engine philox fallback streams are bit to bit identical to the reference random123", Cbrng,
                   alea::philox2x64, alea::philox4x64) {
  pv::run_counter_engine_stream_validation<Cbrng>();
}
