/**
 * Copyright (c) 2026, Adrien Devresse <adev@adev.name>
 *
 * Boost Software License - Version 1.0
 *
 * Permission is hereby granted, free of charge, to any person or organization
 * obtaining a copy of the software and accompanying documentation covered by
 * this license (the "Software") to use, reproduce, display, distribute,
 * execute, and transmit the Software, and to prepare derivative works of the
 * Software, and to permit third-parties to whom the Software is furnished to
 * do so, all subject to the following:
 *
 * The copyright notices in the Software and this entire statement, including
 * the above license grant, this restriction and the following disclaimer,
 * must be included in all copies of the Software, in whole or in part, and
 * all derivative works of the Software, unless such copies or derivative
 * works are solely in the form of machine-executable object code generated by
 * a source language processor.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
 * SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE
 * FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
 * ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
 * DEALINGS IN THE SOFTWARE.
 *
 */

#define DOCTEST_CONFIG_IMPLEMENT_WITH_MAIN
#include "philox_validation_common.hpp"

//
// Validation of the alea philox generators against the reference random123
// implementation. This translation unit exercises the natural multiplication
// path of the platform: the double width integer multiply when it is
// available, the portable fallback otherwise. The fallback is additionally
// validated on its own, when the platform supports the double width type, by
// the philox_fallback_validation.cpp translation unit.
//

namespace pv = alea::test::philox_validation;

TEST_CASE_TEMPLATE("philox blocks are bit to bit identical to the reference random123", AleaCbrng, alea::philox2x32,
                   alea::philox4x32, alea::philox2x64, alea::philox4x64) {
  using ref_type = typename pv::reference_generator<AleaCbrng>::type;
  pv::run_random_block_validation<AleaCbrng, ref_type>();
}

TEST_CASE("philox with non default round counts matches the reference random123") {
  // reduced and degenerate round counts exercise the bounds of the round loop
  // and every injection point of the Weyl key sequence
  pv::run_random_block_validation<alea::philox<4, std::uint64_t, 12>, r123::Philox4x64_R<12>>();
  pv::run_random_block_validation<alea::philox<2, std::uint32_t, 7>, r123::Philox2x32_R<7>>();
  pv::run_random_block_validation<alea::philox<4, std::uint32_t, 1>, r123::Philox4x32_R<1>>();
}

TEST_CASE_TEMPLATE("counter_engine philox streams are bit to bit identical to the reference random123", Cbrng,
                   alea::philox2x32, alea::philox4x32, alea::philox2x64, alea::philox4x64) {
  pv::run_counter_engine_stream_validation<Cbrng>();
}
