/**
 * Copyright (c) 2026, Adrien Devresse <adev@adev.name>
 *
 * Boost Software License - Version 1.0
 *
 * Permission is hereby granted, free of charge, to any person or organization
 * obtaining a copy of the software and accompanying documentation covered by
 * this license (the "Software") to use, reproduce, display, distribute,
 * execute, and transmit the Software, and to prepare derivative works of the
 * Software, and to permit third-parties to whom the Software is furnished to
 * do so, all subject to the following:
 *
 * The copyright notices in the Software and this entire statement, including
 * the above license grant, this restriction and the following disclaimer,
 * must be included in all copies of the Software, in whole or in part, and
 * all derivative works of the Software, unless such copies or derivative
 * works are solely in the form of machine-executable object code generated by
 * a source language processor.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
 * SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE
 * FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
 * ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
 * DEALINGS IN THE SOFTWARE.
 *
 */
#pragma once

#include "doctest/doctest.h"

#include <array>
#include <cstddef>
#include <cstdint>
#include <limits>
#include <random>

#include "Random123/philox.h"

#include "alea/random.hpp"

//
// Helpers shared by the philox validation translation units. The reference
// random123 implementation is fetched at configure time with FetchContent when
// -DENABLE_VALIDATION=ON.
//
// Every check draws its random inputs from a mersenne twister correctly
// initialized from the seed of the unit test framework (doctest --rand-seed,
// 0 by default), mixed with a per test salt. A seed and a counter are drawn
// for each repetition: these two numbers are used as the (key, counter) pair
// of the alea implementation and of the reference implementation, and their
// output blocks must match bit to bit.
//

namespace alea {
namespace test {
namespace philox_validation {

/// reference random123 generator type for a given alea generator
template <typename AleaCbrng> struct reference_generator;

template <> struct reference_generator<alea::philox2x32> {
  using type = r123::Philox2x32;
};

template <> struct reference_generator<alea::philox4x32> {
  using type = r123::Philox4x32;
};

template <> struct reference_generator<alea::philox2x64> {
  using type = r123::Philox2x64;
};

template <> struct reference_generator<alea::philox4x64> {
  using type = r123::Philox4x64;
};

/// fill all the words of the array with the same value
template <typename Array> Array filled_array(typename Array::value_type value) {
  Array array{};
  for (auto& word : array) {
    word = value;
  }
  return array;
}

/// a mersenne twister correctly initialized from the seed of the unit test
/// framework: the doctest rand_seed (--rand-seed on the command line, 0 by
/// default) is mixed with a per test salt, so that every test draws a
/// different sequence, and every run of the suite is reproducible whatever
/// the order of the tests
inline std::mt19937 framework_rng(std::uint32_t salt) {
  const std::uint32_t framework_seed = static_cast<std::uint32_t>(doctest::getContextOptions()->rand_seed);
  std::seed_seq sequence{framework_seed, salt};
  return std::mt19937(sequence);
}

/// a per generator variant salt: every test of the suite draws a different
/// pseudo random sequence from the framework seed
template <typename AleaCbrng> constexpr std::uint32_t generator_salt() {
  using uint_type = typename AleaCbrng::uint_type;
  using domain_type = typename AleaCbrng::domain_type;
  constexpr std::uint32_t n_words = static_cast<std::uint32_t>(domain_type{}.size());
  constexpr std::uint32_t word_bits = static_cast<std::uint32_t>(std::numeric_limits<uint_type>::digits);
  return n_words * 0x01000193u + word_bits * 0x0000B529u + AleaCbrng::number_of_rounds * 0x27D4EB2Fu;
}

/// draw a full width random word from the mersenne twister: 32 bit words need
/// one draw, 64 bit words are assembled from two consecutive draws
template <typename Uint> Uint random_word(std::mt19937& rng) {
  if constexpr (sizeof(Uint) <= 4) {
    return static_cast<Uint>(rng());
  } else {
    return (static_cast<Uint>(rng()) << 32) | static_cast<Uint>(rng());
  }
}

/// check that alea and the reference random123 implementation produce the
/// exact same block for the (key, counter) pair, word by word
template <typename AleaCbrng, typename RefCbrng>
void check_block_equivalence(const typename AleaCbrng::key_type& key, const typename AleaCbrng::domain_type& counter) {
  using uint_type = typename AleaCbrng::uint_type;
  using key_type = typename AleaCbrng::key_type;
  using domain_type = typename AleaCbrng::domain_type;

  static_assert(RefCbrng::rounds == AleaCbrng::number_of_rounds,
                "the reference and alea generators must perform the same number of rounds");

  // philox uses half as many key words as counter words
  typename RefCbrng::ctr_type ref_counter{};
  typename RefCbrng::key_type ref_key{};
  for (std::size_t i = 0; i < counter.size(); ++i) {
    ref_counter[i] = static_cast<uint_type>(counter[i]);
  }
  for (std::size_t i = 0; i < key.size(); ++i) {
    ref_key[i] = static_cast<uint_type>(key[i]);
  }

  RefCbrng ref_cipher;
  const auto ref_block = ref_cipher(ref_counter, ref_key);
  const auto alea_block = AleaCbrng(key)(counter);

  static_assert(key_type{}.size() == domain_type{}.size() / 2,
                "philox must use half as many key words as counter words");
  REQUIRE_EQ(alea_block.size(), ref_block.size());
  for (std::size_t i = 0; i < ref_block.size(); ++i) {
    CHECK_EQ(alea_block[i], static_cast<uint_type>(ref_block[i]));
  }
}

/// draw two random numbers from the mersenne twister, a seed and a counter,
/// broadcast them to the words of the key and of the counter, and check that
/// the alea implementation and the reference implementation produce the exact
/// same block
template <typename AleaCbrng, typename RefCbrng> void check_random_block(std::mt19937& rng) {
  using key_type = typename AleaCbrng::key_type;
  using domain_type = typename AleaCbrng::domain_type;
  using uint_type = typename AleaCbrng::uint_type;

  const uint_type seed_word = random_word<uint_type>(rng);
  const uint_type counter_word = random_word<uint_type>(rng);

  check_block_equivalence<AleaCbrng, RefCbrng>(filled_array<key_type>(seed_word),
                                               filled_array<domain_type>(counter_word));
}

/// repeat the random seed / counter block check 2048 times
template <typename AleaCbrng, typename RefCbrng> void run_random_block_validation() {
  constexpr std::size_t n_repetitions = 2048;

  std::mt19937 rng = framework_rng(generator_salt<AleaCbrng>());
  for (std::size_t i = 0; i < n_repetitions; ++i) {
    check_random_block<AleaCbrng, RefCbrng>(rng);
  }
}

/// check that a counter_engine stream is bit to bit identical to the reference
/// random123 implementation over 2048 blocks
template <typename Cbrng> void run_counter_engine_stream_validation() {
  using engine_type = alea::counter_engine<Cbrng>;
  using ref_type = typename reference_generator<Cbrng>::type;
  using ref_ctr_type = typename ref_type::ctr_type;
  using ref_key_type = typename ref_type::key_type;
  using result_type = typename engine_type::result_type;
  using key_type = typename engine_type::key_type;
  using ctr_type = typename engine_type::ctr_type;

  constexpr std::size_t words_per_block = ctr_type{}.size();
  constexpr std::size_t n_repetitions = 2048;
  constexpr std::size_t n_blocks = 32;

  std::mt19937 rng = framework_rng(generator_salt<Cbrng>() + 0xDEECE66Du);

  for (std::size_t rep = 0; rep < n_repetitions; ++rep) {
    // one random number broadcasted to every word of the key
    const result_type seed_word = random_word<result_type>(rng);
    const key_type seed = filled_array<key_type>(seed_word);

    ref_key_type ref_key{};
    for (std::size_t i = 0; i < seed.size(); ++i) {
      ref_key[i] = static_cast<result_type>(seed[i]);
    }

    // the engine encrypts the counters 1, 2, 3, ... and emits the words of
    // each block from the most significant to the least significant one
    ref_ctr_type ref_counter{};
    ref_ctr_type ref_block{};
    ref_type ref_cipher;
    engine_type engine(seed);

    for (std::size_t i = 0; i < n_blocks * words_per_block; ++i) {
      if (i % words_per_block == 0) {
        ref_counter.incr();
        ref_block = ref_cipher(ref_counter, ref_key);
      }
      const std::size_t word_index = words_per_block - 1 - (i % words_per_block);
      CHECK_EQ(engine(), static_cast<result_type>(ref_block[word_index]));
    }
  }
}

} // namespace philox_validation
} // namespace test
} // namespace alea
