/**
 * Copyright (c) 2026, Adrien Devresse <adev@adev.name>
 *
 * Boost Software License - Version 1.0
 *
 * Permission is hereby granted, free of charge, to any person or organization
 * obtaining a copy of the software and accompanying documentation covered by
 * this license (the "Software") to use, reproduce, display, distribute,
 * execute, and transmit the Software, and to prepare derivative works of the
 * Software, and to permit third-parties to whom the Software is furnished to
 * do so, all subject to the following:
 *
 * The copyright notices in the Software and this entire statement, including
 * the above license grant, this restriction and the following disclaimer,
 * must be included in all copies of the Software, in whole or in part, and
 * all derivative works of the Software, unless such copies or derivative
 * works are solely in the form of machine-executable object code generated by
 * a source language processor.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
 * SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE
 * FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
 * ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
 * DEALINGS IN THE SOFTWARE.
 *
 */

#define DOCTEST_CONFIG_IMPLEMENT_WITH_MAIN
#include "doctest/doctest.h"

#include <algorithm>
#include <array>
#include <cstddef>
#include <cstdint>
#include <cstring>
#include <random>
#include <span>
#include <vector>

// the reference header is plain C and does not provide the extern "C" guards
extern "C" {
#include "sha256.h"
}

#include "alea/sha256.hpp"

//
// Validation of alea sha256 against a reference C implementation of SHA-256
// (https://github.com/B-Con/crypto-algorithms, sha256.c), fetched at
// configure time with FetchContent when -DALEA_ENABLE_VALIDATION_SHA256=ON.
//
// For a broad range of message sizes, a deterministic pseudo random message
// is hashed with the reference one shot function and with the alea streaming
// hasher fed in random chunks. The two digests must match bit to bit.
//

namespace {

std::vector<std::byte> random_message(std::mt19937_64& rng, std::size_t size) {
  std::uniform_int_distribution<unsigned int> byte(0, 255);
  std::vector<std::byte> message(size);
  for (std::size_t i = 0; i < size; ++i) {
    message[i] = static_cast<std::byte>(byte(rng));
  }
  return message;
}

std::vector<std::size_t> test_sizes() {
  std::vector<std::size_t> sizes;
  for (std::size_t size = 0; size <= 300; ++size) {
    sizes.push_back(size);
  }
  for (const std::size_t size : {511u, 512u, 513u, 1000u, 4096u, 65536u, 100000u}) {
    sizes.push_back(size);
  }
  return sizes;
}

std::array<std::byte, 32> reference_sha256(const std::vector<std::byte>& message) {
  SHA256_CTX context;
  sha256_init(&context);
  sha256_update(&context, reinterpret_cast<const BYTE*>(message.data()), message.size());
  std::array<std::byte, 32> digest{};
  sha256_final(&context, reinterpret_cast<BYTE*>(digest.data()));
  return digest;
}

} // namespace

TEST_CASE("sha256 matches the reference implementation") {
  std::mt19937_64 rng(0x5eed9abcu);
  std::uniform_int_distribution<std::size_t> chunk_size(1, 200);

  for (const std::size_t size : test_sizes()) {
    const std::vector<std::byte> message = random_message(rng, size);
    const std::array<std::byte, 32> expected = reference_sha256(message);

    for (int trial = 0; trial < 3; ++trial) {
      alea::sha256 hasher;
      for (std::size_t position = 0; position < message.size();) {
        const std::size_t chunk = std::min(chunk_size(rng), message.size() - position);
        hasher.update(std::span<const std::byte>(message.data() + position, chunk));
        position += chunk;
      }
      const alea::sha256::digest_type digest = hasher.finalize();
      REQUIRE(std::memcmp(digest.data(), expected.data(), expected.size()) == 0);
    }
  }
}
