/**
 * Copyright (c) 2026, Adrien Devresse <adev@adev.name>
 *
 * Boost Software License - Version 1.0
 *
 * Permission is hereby granted, free of charge, to any person or organization
 * obtaining a copy of the software and accompanying documentation covered by
 * this license (the "Software") to use, reproduce, display, distribute,
 * execute, and transmit the Software, and to prepare derivative works of the
 * Software, and to permit third-parties to whom the Software is furnished to
 * do so, all subject to the following:
 *
 * The copyright notices in the Software and this entire statement, including
 * the above license grant, this restriction and the following disclaimer,
 * must be included in all copies of the Software, in whole or in part, and
 * all derivative works of the Software, unless such copies or derivative
 * works are solely in the form of machine-executable object code generated by
 * a source language processor.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
 * SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE
 * FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
 * ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
 * DEALINGS IN THE SOFTWARE.
 *
 */

#define DOCTEST_CONFIG_IMPLEMENT_WITH_MAIN
#include "doctest/doctest.h"

#include <array>
#include <cstddef>
#include <cstdint>
#include <stdexcept>
#include <string>
#include <tuple>
#include <vector>

#include <cuda_runtime.h>

#include "alea/random.hpp"

//
// CUDA unit tests of alea.
//
// The very same headers used on the host are compiled by nvcc here, so these
// tests check that the single source annotations of gpu_portability.hpp are
// correct: every generator must return on the device exactly what it returns
// on the host.
//
// The device coverage is deliberately large: every cipher test launches
// 1024 blocks of maxThreadsPerBlock threads (about one million threads) and
// compares every single generated block with the host reference.
//

namespace {

/// throw a std::runtime_error carrying the CUDA error of `code`
void check_cuda(cudaError_t code, const char* expr, const char* file, int line) {
  if (code != cudaSuccess) {
    throw std::runtime_error(std::string("CUDA error: ") + cudaGetErrorString(code) + " (" + expr + ") at " + file +
                             ":" + std::to_string(line));
  }
}

#define ALEA_CUDA_CHECK(expr) check_cuda((expr), #expr, __FILE__, __LINE__)

/// the launch configuration used by the large kernels:
/// 1024 blocks of the maximum number of threads per block
struct launch_config {
  unsigned blocks;
  unsigned threads;
};

launch_config large_config() {
  static const launch_config config = [] {
    int device = 0;
    ALEA_CUDA_CHECK(cudaGetDevice(&device));
    cudaDeviceProp properties{};
    ALEA_CUDA_CHECK(cudaGetDeviceProperties(&properties, device));
    return launch_config{1024u, static_cast<unsigned>(properties.maxThreadsPerBlock)};
  }();
  return config;
}

/// a launch configuration for the ARS generators
///
/// ARS relies on the software AES round on the device, which needs around 120
/// registers per thread: launching the maximum number of threads per block
/// would exceed the register file. A smaller block size with more blocks keeps
/// the same total number of threads (about one million).
launch_config software_aes_config() { return launch_config{4096u, 256u}; }

/// deterministic key derived from a linear index, reproducible on host and device
template <typename CBRNG> ALEA_HOST_DEVICE typename CBRNG::key_type make_key(std::uint64_t seed) {
  typename CBRNG::key_type key{};
  std::uint64_t state = seed + UINT64_C(0x9E3779B97F4A7C15);
  for (std::size_t i = 0; i < key.size(); ++i) {
    state += UINT64_C(0x9E3779B97F4A7C15);
    std::uint64_t z = state;
    z = (z ^ (z >> 30)) * UINT64_C(0xBF58476D1CE4E5B9);
    z = (z ^ (z >> 27)) * UINT64_C(0x94D049BB133111EB);
    key[i] = static_cast<typename CBRNG::uint_type>(z ^ (z >> 31));
  }
  return key;
}

/// deterministic counter derived from a linear index, reproducible on host and device
template <typename CBRNG> ALEA_HOST_DEVICE typename CBRNG::domain_type make_counter(std::uint64_t seed) {
  typename CBRNG::domain_type counter{};
  std::uint64_t state = seed + UINT64_C(0xD1B54A32D192ED03);
  for (std::size_t i = 0; i < counter.size(); ++i) {
    state += UINT64_C(0x9E3779B97F4A7C15);
    std::uint64_t z = state;
    z = (z ^ (z >> 29)) * UINT64_C(0xBF58476D1CE4E5B9);
    counter[i] = static_cast<typename CBRNG::uint_type>(z ^ (z >> 32));
  }
  return counter;
}

/// encrypt, on the device, the counter derived from the linear thread index
template <typename CBRNG> __global__ void cipher_kernel(typename CBRNG::range_type* out, std::uint64_t count) {
  const std::uint64_t i = static_cast<std::uint64_t>(blockIdx.x) * blockDim.x + threadIdx.x;
  if (i >= count) {
    return;
  }
  const CBRNG cipher(make_key<CBRNG>(i));
  out[i] = cipher(make_counter<CBRNG>(i));
}

/// run `draws` rounded values of a counter_engine, on the device, for each thread
template <typename CBRNG>
__global__ void engine_kernel(typename CBRNG::uint_type* out, std::uint64_t count, unsigned draws) {
  const std::uint64_t i = static_cast<std::uint64_t>(blockIdx.x) * blockDim.x + threadIdx.x;
  if (i >= count) {
    return;
  }
  alea::counter_engine<CBRNG> engine(make_key<CBRNG>(i));
  // exercise discard() as well: the buffered block handling runs on the device
  engine.discard(i % 8);
  typename CBRNG::uint_type acc = 0;
  for (unsigned d = 0; d < draws; ++d) {
    acc ^= static_cast<typename CBRNG::uint_type>(engine());
  }
  out[i] = acc;
}

/// encrypt one explicit (key, counter) pair on the device and return the words
template <typename CBRNG>
__global__ void golden_kernel(const typename CBRNG::key_type key, const typename CBRNG::domain_type counter,
                              unsigned long long* out) {
  const CBRNG cipher(key);
  const typename CBRNG::range_type block = cipher(counter);
  for (std::size_t i = 0; i < block.size(); ++i) {
    out[i] = static_cast<unsigned long long>(block[i]);
  }
}

/// check that a full grid of device generated blocks matches the host reference
template <typename CBRNG> void check_cipher_matches_host(launch_config config = large_config()) {
  const std::size_t count = static_cast<std::size_t>(config.blocks) * config.threads;

  typename CBRNG::range_type* device_out = nullptr;
  ALEA_CUDA_CHECK(cudaMalloc(&device_out, count * sizeof(typename CBRNG::range_type)));
  cipher_kernel<CBRNG><<<config.blocks, config.threads>>>(device_out, count);
  ALEA_CUDA_CHECK(cudaGetLastError());
  ALEA_CUDA_CHECK(cudaDeviceSynchronize());

  std::vector<typename CBRNG::range_type> host_out(count);
  ALEA_CUDA_CHECK(
      cudaMemcpy(host_out.data(), device_out, count * sizeof(typename CBRNG::range_type), cudaMemcpyDeviceToHost));
  ALEA_CUDA_CHECK(cudaFree(device_out));

  std::size_t mismatches = 0;
  std::size_t first_mismatch = 0;
  for (std::size_t i = 0; i < count; ++i) {
    const CBRNG cipher(make_key<CBRNG>(i));
    const typename CBRNG::range_type expected = cipher(make_counter<CBRNG>(i));
    if (host_out[i] != expected) {
      if (mismatches == 0) {
        first_mismatch = i;
      }
      mismatches += 1;
    }
  }

  CAPTURE(first_mismatch);
  CHECK_EQ(mismatches, std::size_t{0});
}

/// check that a full grid of device run counter_engine matches the host reference
template <typename CBRNG> void check_engine_matches_host(unsigned draws, launch_config config = large_config()) {
  const std::size_t count = static_cast<std::size_t>(config.blocks) * config.threads;

  typename CBRNG::uint_type* device_out = nullptr;
  ALEA_CUDA_CHECK(cudaMalloc(&device_out, count * sizeof(typename CBRNG::uint_type)));
  engine_kernel<CBRNG><<<config.blocks, config.threads>>>(device_out, count, draws);
  ALEA_CUDA_CHECK(cudaGetLastError());
  ALEA_CUDA_CHECK(cudaDeviceSynchronize());

  std::vector<typename CBRNG::uint_type> host_out(count);
  ALEA_CUDA_CHECK(
      cudaMemcpy(host_out.data(), device_out, count * sizeof(typename CBRNG::uint_type), cudaMemcpyDeviceToHost));
  ALEA_CUDA_CHECK(cudaFree(device_out));

  std::size_t mismatches = 0;
  std::size_t first_mismatch = 0;
  for (std::size_t i = 0; i < count; ++i) {
    alea::counter_engine<CBRNG> engine(make_key<CBRNG>(i));
    engine.discard(i % 8);
    typename CBRNG::uint_type acc = 0;
    for (unsigned d = 0; d < draws; ++d) {
      acc ^= static_cast<typename CBRNG::uint_type>(engine());
    }
    if (host_out[i] != acc) {
      if (mismatches == 0) {
        first_mismatch = i;
      }
      mismatches += 1;
    }
  }

  CAPTURE(first_mismatch);
  CHECK_EQ(mismatches, std::size_t{0});
}

/// run golden_kernel and return the generated words
template <typename CBRNG>
std::vector<unsigned long long> run_golden(const typename CBRNG::key_type& key,
                                           const typename CBRNG::domain_type& counter) {
  constexpr std::size_t word_count = std::tuple_size<typename CBRNG::domain_type>::value;

  unsigned long long* device_out = nullptr;
  ALEA_CUDA_CHECK(cudaMalloc(&device_out, word_count * sizeof(unsigned long long)));
  golden_kernel<CBRNG><<<1, 1>>>(key, counter, device_out);
  ALEA_CUDA_CHECK(cudaGetLastError());
  ALEA_CUDA_CHECK(cudaDeviceSynchronize());

  std::vector<unsigned long long> host_out(word_count);
  ALEA_CUDA_CHECK(
      cudaMemcpy(host_out.data(), device_out, word_count * sizeof(unsigned long long), cudaMemcpyDeviceToHost));
  ALEA_CUDA_CHECK(cudaFree(device_out));
  return host_out;
}

} // namespace

TEST_CASE("threefry runs on the GPU") {
  SUBCASE("golden values") {
    const std::vector<unsigned long long> block =
        run_golden<alea::threefry4x64>(alea::threefry4x64::key_type{}, alea::threefry4x64::domain_type{1, 2, 3, 4});
    CHECK_EQ(block.size(), std::size_t{4});
    CHECK_EQ(block[0], 14276687134489684560ULL);
    CHECK_EQ(block[1], 12958816754744280892ULL);
    CHECK_EQ(block[2], 17894100595138145301ULL);
    CHECK_EQ(block[3], 1013103230217800475ULL);
  }

  SUBCASE("full grid matches the host, every word width") {
    check_cipher_matches_host<alea::threefry2x32>();
    check_cipher_matches_host<alea::threefry4x32>();
    check_cipher_matches_host<alea::threefry2x64>();
    check_cipher_matches_host<alea::threefry4x64>();
  }

  SUBCASE("counter_engine runs on the device") {
    check_engine_matches_host<alea::threefry2x32>(4);
    check_engine_matches_host<alea::threefry4x32>(4);
    check_engine_matches_host<alea::threefry2x64>(4);
    check_engine_matches_host<alea::threefry4x64>(4);
  }
}

TEST_CASE("philox runs on the GPU") {
  SUBCASE("golden values") {
    const std::vector<unsigned long long> block =
        run_golden<alea::philox4x64>(alea::philox4x64::key_type{}, alea::philox4x64::domain_type{1, 2, 3, 4});
    CHECK_EQ(block.size(), std::size_t{4});
    CHECK_EQ(block[0], 5012960473186433633ULL);
    CHECK_EQ(block[1], 12081579199819527121ULL);
    CHECK_EQ(block[2], 4264790475553368732ULL);
    CHECK_EQ(block[3], 6866478666125097096ULL);
  }

  SUBCASE("full grid matches the host, every word width") {
    check_cipher_matches_host<alea::philox2x32>();
    check_cipher_matches_host<alea::philox4x32>();
    check_cipher_matches_host<alea::philox2x64>();
    check_cipher_matches_host<alea::philox4x64>();
  }

  SUBCASE("counter_engine runs on the device") {
    check_engine_matches_host<alea::philox2x32>(4);
    check_engine_matches_host<alea::philox4x32>(4);
    check_engine_matches_host<alea::philox2x64>(4);
    check_engine_matches_host<alea::philox4x64>(4);
  }
}

TEST_CASE("ars runs on the GPU") {
  SUBCASE("golden values") {
    const std::vector<unsigned long long> block =
        run_golden<alea::ars4x32>(alea::ars4x32::key_type{}, alea::ars4x32::domain_type{1, 2, 3, 4});
    CHECK_EQ(block.size(), std::size_t{4});
    CHECK_EQ(block[0], 0xb427c7f2ULL);
    CHECK_EQ(block[1], 0xee4ef3dfULL);
    CHECK_EQ(block[2], 0x66d36578ULL);
    CHECK_EQ(block[3], 0x268d303eULL);
  }

  SUBCASE("full grid matches the host, every round count") {
    check_cipher_matches_host<alea::ars<5>>(software_aes_config());
    check_cipher_matches_host<alea::ars<7>>(software_aes_config());
    check_cipher_matches_host<alea::ars<10>>(software_aes_config());
  }

  SUBCASE("counter_engine runs on the device") {
    check_engine_matches_host<alea::ars<5>>(4, software_aes_config());
    check_engine_matches_host<alea::ars<7>>(4, software_aes_config());
    check_engine_matches_host<alea::ars<10>>(4, software_aes_config());
  }
}